(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=v=>String(v||'').replace(/\s+/g,' ').trim().toLowerCase();
  const ICON={
    home:'<svg viewBox="0 0 24 24"><path d="M3 11 12 4l9 7v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1Z"/></svg>',
    users:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2.3"/><path d="M3 20v-2a5 5 0 0 1 5-5h2a5 5 0 0 1 5 5v2M15 14a4 4 0 0 1 6 3.5V20"/></svg>',
    calendar:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>',
    wallet:'<svg viewBox="0 0 24 24"><rect x="3" y="6" width="18" height="14" rx="2"/><path d="M3 10h18M15 14h6"/></svg>',
    shield:'<svg viewBox="0 0 24 24"><path d="M12 3 20 6v6c0 5-3.4 8-8 10-4.6-2-8-5-8-10V6Z"/><path d="m8.5 12 2.3 2.3 4.7-4.8"/></svg>',
    headset:'<svg viewBox="0 0 24 24"><path d="M4 13v-2a8 8 0 0 1 16 0v2M4 13h3v6H5a2 2 0 0 1-2-2v-2a2 2 0 0 1 1-2ZM20 13h-3v6h2a2 2 0 0 0 2-2v-2a2 2 0 0 0-1-2Z"/></svg>',
    audit:'<svg viewBox="0 0 24 24"><path d="M5 4h14v16H5zM8 8h8M8 12h8M8 16h5"/></svg>',
    chart:'<svg viewBox="0 0 24 24"><path d="M4 20V10M10 20V5M16 20v-8M22 20H2"/></svg>',
    link:'<svg viewBox="0 0 24 24"><path d="M10 13a5 5 0 0 0 7.1.1l2-2a5 5 0 0 0-7.1-7.1l-1.1 1.1M14 11a5 5 0 0 0-7.1-.1l-2 2A5 5 0 0 0 12 20l1.1-1.1"/></svg>',
    alert:'<svg viewBox="0 0 24 24"><path d="M12 4 22 20H2Z"/><path d="M12 9v4M12 17h.01"/></svg>',
    rupee:'<svg viewBox="0 0 24 24"><path d="M6 5h12M6 9h12M6 5c5 0 6 7 0 7h3l7 7"/></svg>',
    building:'<svg viewBox="0 0 24 24"><path d="M4 21V7l8-4 8 4v14M8 10h2M14 10h2M8 14h2M14 14h2M9 21v-3h6v3"/></svg>',
    clock:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/></svg>',
    eye:'<svg viewBox="0 0 24 24"><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/></svg>'
  };
  const C={
    COOPERATIVE_ADMIN:{name:'Cooperative Admin',scope:'Local cooperative scope',online:'Service Online',kicker:'WELCOME BACK',title:'Cooperative Operations Dashboard',sub:'Manage workers, services, verification, complaints and local capacity in one place.',note:'Stronger\nLocal Communities',refresh:'Refresh Local Data',section:'LOCAL SOCIETY OPERATIONS',entity:'YUKTI Kolhapur Services Cooperative',place:'Kolhapur · Local cooperative scope',foot:'Stronger Communities\nThrough Dignified Work',nav:[['overview','Overview','Dashboard & insights','home','home'],['workers','Workers','Directory & availability','users','#coop-workers'],['services','Bookings & Services','Active services','calendar','#coop-services'],['payments','Payments & Earnings','Transactions & reports','wallet','#coop-payments'],['sep'],['verification','Trust & Verification','Identity, skills & documents','shield','#coop-verification'],['complaints','Complaints & SLA','Grievances & resolution','headset','#coop-complaints'],['activity','Audit & Activity','Activity logs & traceability','audit','#coop-activity'],['sep'],['capacity','Local Capacity','Demand & workforce gaps','chart','#coop-capacity'],['planning','Demand & Planning','Forecast & planning','chart','tab:planning']]},
    FEDERATION_ADMIN:{name:'Federation Admin',scope:'Regional oversight',online:'Network Online',kicker:'FEDERATION OPERATIONS',title:'Federation Operations Dashboard',sub:'Monitor connected cooperatives, cross-cooperative assignments, escalations and regional capacity in one place.',note:'Stronger\nCooperatives\nA Stronger Region',refresh:'Refresh Federation Data',section:'FEDERATION NETWORK OVERVIEW',entity:'Kolhapur Regional Federation',place:'Kolhapur region · Federation scope',foot:'Regional visibility.\nStronger local cooperatives.',nav:[['overview','Overview','Federation dashboard','home','home'],['network','Connected Cooperatives','Network & member societies','users','#fed-network'],['assignments','Cross-Coop Assignments','Shared capacity & coordination','link','tab:capacity'],['complaints','Complaints & Escalations','Inter-cooperative grievances','alert','tab:complaint'],['verification','Trust & Verification','Standards across network','shield','tab:trust'],['capacity','Capacity & Demand','Regional planning & insights','chart','tab:planning'],['payments','Payments & Settlements','Cross-coop transactions','wallet','#fed-records'],['reports','Reports & Audit','Governance & compliance','audit','tab:golden']]}
  };
  let activeRole='',activeKey='overview',timer=0;
  function role(){const a=String(window.SanPaidAuth?.getRole?.()||'').toUpperCase();if(C[a])return a;const s=$('#sihJudgeShell'),d=String(s?.dataset?.adminRole||'').toUpperCase();if(C[d])return d;return s?.classList.contains('federation-govtech')?'FEDERATION_ADMIN':s?.classList.contains('cooperative-govtech')?'COOPERATIVE_ADMIN':'';}
  function visible(){const s=$('#sihJudgeShell');return !!s&&!s.classList.contains('judge-hidden')&&!!C[role()];}
  function now(){return new Date().toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});}
  function read(rootSel,label){const root=$(rootSel),want=norm(label);if(!root)return'';for(const card of $$('article,button,.admin-attention-card',root)){if(norm($('span',card)?.textContent)!==want)continue;return String($('strong,b',card)?.textContent||'').trim();}return'';}
  function fallback(r,label){if(!window.SanPaidReviewRuntime?.enabled)return'—';const coop={'verification attention':'2','open complaints':'1','sla breaches':'0','capacity requests':'1','total workers':'3','verified workers':'2','available workers':'2','active services':'4','recorded payments':'12'};const fed={'connected cooperatives':'8','cross-coop assignments':'12','escalated complaints':'2','repeated shortage signals':'5','verified workers':'126','active cross-coop jobs':'12','open escalations':'2','unfulfilled requests':'9','recorded settlements':'18'};return(r==='COOPERATIVE_ADMIN'?coop:fed)[norm(label)]??'—';}
  function val(label,sel,r){return read(sel,label)||fallback(r,label);}
  function num(v){const n=Number(String(v).replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0;}
  function stat(tone,icon,label,value,detail,key){return `<article class="af-stat-card ${tone}"><span class="af-stat-icon">${ICON[icon]}</span><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(detail)}</small><button type="button" class="af-stat-link" data-af-key="${esc(key)}">View details →</button></article>`;}
  function mini(icon,label,value,detail){return `<article class="af-mini-card"><span class="af-mini-icon">${ICON[icon]}</span><div><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(detail)}</small></div></article>`;}
  function nav(cfg){return cfg.nav.map(x=>x[0]==='sep'?'<div class="af-nav-sep"></div>':`<button type="button" data-af-key="${esc(x[0])}" class="${x[0]==='overview'?'active':''}">${ICON[x[3]]}<b>${esc(x[1])}</b><small>${esc(x[2])}</small></button>`).join('');}
  function dataFor(r){
    if(r==='COOPERATIVE_ADMIN')return {attention:[['teal','shield','Verification Attention',val('Verification Attention','#adminAttentionGrid',r),'Documents need review','verification'],['red','alert','Open Complaints',val('Open Complaints','#adminAttentionGrid',r),'Needs follow-up','complaints'],['amber','clock','SLA Breaches',val('SLA Breaches','#adminAttentionGrid',r),'Requires attention','complaints'],['blue','users','Capacity Requests',val('Capacity Requests','#adminAttentionGrid',r),'Needs coordination','capacity']],overview:[['users','Total Workers',val('Total Workers','#coopKpis',r),'Registered in this cooperative'],['shield','Verified Workers',val('Verified Workers','#coopKpis',r),'Identity verification completed'],['users','Available Workers',val('Available Workers','#coopKpis',r),'Verified + currently available'],['chart','Active Services',val('Active Services','#coopKpis',r),'Currently running services'],['headset','Open Complaints',val('Open Complaints','#coopKpis',r),'Requiring follow-up'],['rupee','Recorded Payments',val('Recorded Payments','#coopKpis',r),'Transactions this month']]};
    const src='#fedNetworkKpis',connected=read(src,'Active Cooperatives')||fallback(r,'Connected Cooperatives'),verified=read(src,'Verified Workers')||fallback(r,'Verified Workers'),capacity=read(src,'Capacity Requests')||fallback(r,'Unfulfilled Requests'),escal=read(src,'Open Escalations')||fallback(r,'Open Escalations'),gap=read(src,'Regional Capacity Gap'),assign=fallback(r,'Cross-Coop Assignments'),shortage=gap?String(Math.max(0,num(gap))):fallback(r,'Repeated Shortage Signals');
    return {attention:[['teal','building','Connected Cooperatives',connected,'Active in the federation','network'],['blue','link','Cross-Coop Assignments',assign,'Governed shared-capacity jobs','assignments'],['red','alert','Escalated Complaints',escal,'Need federation attention','complaints'],['amber','chart','Repeated Shortage Signals',shortage,'Human-reviewed planning inputs','capacity']],overview:[['building','Connected Cooperatives',connected,'Member societies'],['users','Verified Workers',verified,'Across all cooperatives'],['wallet','Active Cross-Coop Jobs',assign,'Under federation coordination'],['alert','Open Escalations',escal,'Require federation action'],['chart','Unfulfilled Requests',capacity,'From cooperatives'],['rupee','Recorded Settlements',fallback(r,'Recorded Settlements'),'Cross-coop transactions this month']]};
  }
  function lists(r,d){if(r==='COOPERATIVE_ADMIN'){const v=num(d.attention[0][3])||2,c=num(d.attention[1][3])||1,cap=num(d.attention[3][3])||1;return{alerts:[['risk',`${c} new complaint received`,'2 hours ago'],['warn',`${v} worker documents pending verification`,'5 hours ago'],['ok','All services running normally','1 day ago']],tasks:[`Review ${v} pending worker verifications`,`Follow up on ${c} open complaint`,`Check ${cap} new capacity request`]};}const e=num(d.attention[2][3])||2,a=num(d.attention[1][3])||12;return{alerts:[['risk',`${e} inter-cooperative complaint escalated`,'2 hours ago'],['warn',`${Math.min(a,2)} cross-coop assignments awaiting review`,'5 hours ago'],['ok','Repeated shortage in electrical services','1 day ago']],tasks:[`Review ${e} escalated complaints`,'Check 1 SLA breach across cooperatives','Review shortage pattern for electricians']};}
  function trust(){return `<div class="af-trust-row"><span>${ICON.eye}Network visibility</span><span>${ICON.users}Cross-coop governance</span><span>${ICON.shield}Escalation oversight</span><span>${ICON.chart}Human-reviewed planning</span></div>`;}
  function dashboard(r){const cfg=C[r],d=dataFor(r),l=lists(r,d),fed=r==='FEDERATION_ADMIN';return `<section class="af-dashboard" id="afDashboard"><section class="af-hero"><div class="af-hero-copy"><span class="af-kicker">${esc(cfg.kicker)}</span><h1>${esc(cfg.title)}</h1><p>${esc(cfg.sub)}</p>${fed?trust():''}</div><button type="button" class="af-refresh" id="afRefresh">↻ &nbsp; ${esc(cfg.refresh)}</button><div class="af-hero-art"><span class="af-hero-note">${esc(cfg.note).replaceAll('\n','<br>')}</span></div></section><section class="af-attention-grid">${d.attention.map(x=>stat(...x)).join('')}</section><section class="af-network"><div class="af-section-head"><div><span class="af-section-kicker">${esc(cfg.section)}</span><h2>${esc(cfg.entity)}</h2></div><span class="af-scope">⌖ ${esc(cfg.place)}</span></div><div class="af-overview-grid ${fed?'federation':''}">${d.overview.map(x=>mini(...x)).join('')}</div></section><section class="af-bottom-grid"><article class="af-list-card"><div class="af-list-title"><h3>● &nbsp; Recent Alerts</h3><button type="button" data-af-key="${fed?'complaints':'activity'}">View all →</button></div><div class="af-list">${l.alerts.map(([t,x,time])=>`<div class="af-list-row ${t}"><i></i><span>${esc(x)}</span><small>${esc(time)}</small></div>`).join('')}</div></article><article class="af-list-card"><div class="af-list-title"><h3>☑ &nbsp; Today's Tasks</h3><button type="button" data-af-key="${fed?'reports':'activity'}">View all →</button></div><div class="af-list">${l.tasks.map(x=>`<div class="af-task-row"><i></i><span>${esc(x)}</span><small>Due today</small></div>`).join('')}</div></article></section></section>`;}
  function markup(r){const cfg=C[r];return `<div id="adminFinalApp"><header class="af-topbar"><div class="af-brand"><button type="button" class="af-mobile-menu" id="afMobileMenu" aria-label="Open navigation">☰</button><img src="app-icon.svg" alt=""><div><strong>San<span>Paid</span></strong><small>Cooperative Workforce Network</small></div></div><div class="af-top-actions"><span class="af-pill online"><i class="af-dot"></i>${esc(cfg.online)}</span><span class="af-pill">${ICON.clock}<span id="afLastSync">Last sync: ${esc(now())}</span></span><div class="af-profile">${ICON.users}<span class="af-profile-copy"><b>${esc(cfg.name)}</b><small>${esc(cfg.scope)}</small></span></div></div></header><div class="af-layout"><aside class="af-sidebar"><nav class="af-nav">${nav(cfg)}</nav><div class="af-side-foot"><span class="af-community-icon"><i></i><i></i><i></i></span><small>${esc(cfg.foot).replaceAll('\n','<br>')}</small></div></aside><main class="af-main">${dashboard(r)}<section class="af-detail-stage" id="afDetailStage" hidden><div class="af-detail-head"><div class="af-detail-title"><h1 id="afDetailTitle">Module</h1><p id="afDetailSubtitle">Operational workspace</p></div><button type="button" class="af-back" data-af-key="overview">← Back to Overview</button></div><div class="af-detail-body" id="afDetailBody"></div></section></main></div></div>`;}
  function setActive(key){$$('#adminFinalApp .af-nav [data-af-key]').forEach(b=>b.classList.toggle('active',b.dataset.afKey===key));}
  function showNode(node){const body=$('#afDetailBody');if(!body||!node)return false;$$(':scope>[data-af-moved="1"]',body).forEach(x=>x.hidden=true);node.dataset.afMoved='1';node.hidden=false;body.appendChild(node);return true;}
  function openKey(key){const cfg=C[activeRole],item=cfg?.nav.find(x=>x[0]===key);if(!item)return;activeKey=key;setActive(key);$('#adminFinalApp')?.classList.remove('nav-open');const dash=$('#afDashboard'),stage=$('#afDetailStage');if(key==='overview'){if(dash)dash.hidden=false;if(stage)stage.hidden=true;return;}if(dash)dash.hidden=true;if(stage)stage.hidden=false;$('#afDetailTitle').textContent=item[1];$('#afDetailSubtitle').textContent=item[2];const target=item[4];if(target.startsWith('#')){if(showNode($(target)))return;setTimeout(()=>showNode($(target))||fallbackPanel(key),350);return;}if(target.startsWith('tab:')){window.SanPaidJudgeMode?.switchTab?.(target.slice(4));setTimeout(()=>showNode($('#sihJudgeShell .judge-section.active'))||fallbackPanel(key),180);return;}fallbackPanel(key);}
  function fallbackPanel(key){const body=$('#afDetailBody');if(!body)return;let n=$(`[data-af-fallback="${key}"]`,body);if(!n){n=document.createElement('div');n.dataset.afFallback=key;n.className='admin-health-error';n.textContent='This module is preparing. Return to Overview and open it again in a moment.';body.appendChild(n);}n.hidden=false;}
  function refresh(){const old=$('#adminHealthRefresh');old?.click();window.dispatchEvent(new CustomEvent('sanpaid:connected-sync',{detail:{source:'admin-final-refresh'}}));const b=$('#afRefresh');if(b){b.disabled=true;b.textContent='Refreshing…';}setTimeout(()=>{const host=$('#afDashboard');if(host){const wrap=document.createElement('div');wrap.innerHTML=dashboard(activeRole);host.replaceWith(wrap.firstElementChild);bindDashboard();}const sync=$('#afLastSync');if(sync)sync.textContent=`Last sync: ${now()}`;},650);}
  function bindDashboard(){const root=$('#afDashboard');if(!root)return;$('#afRefresh',root)?.addEventListener('click',refresh);root.querySelectorAll('[data-af-key]').forEach(b=>b.addEventListener('click',()=>openKey(b.dataset.afKey)));}
  function bind(){const app=$('#adminFinalApp');if(!app)return;app.addEventListener('click',e=>{const b=e.target.closest('[data-af-key]');if(b&&!b.closest('#afDashboard'))openKey(b.dataset.afKey);});$('#afMobileMenu',app)?.addEventListener('click',()=>app.classList.toggle('nav-open'));bindDashboard();}
  function mount(){if(!visible())return;const r=role(),shell=$('#sihJudgeShell'),content=$('#judgeContent');if(!shell||!content)return;shell.classList.add('admin-final-active');if(r===activeRole&&$('#adminFinalApp'))return;activeRole=r;activeKey='overview';$('#adminFinalApp')?.remove();content.insertAdjacentHTML('afterbegin',markup(r));bind();}
  function cleanup(){const s=$('#sihJudgeShell');s?.classList.remove('admin-final-active');$('#adminFinalApp')?.remove();activeRole='';activeKey='overview';}
  function schedule(){clearTimeout(timer);timer=setTimeout(()=>{if(visible())mount();else if($('#adminFinalApp'))cleanup();},120);}
  new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class','data-admin-role']});window.addEventListener('sanpaid:connected-sync',schedule);document.addEventListener('DOMContentLoaded',schedule,{once:true});setTimeout(schedule,0);setTimeout(schedule,900);
})();
