(() => {
  'use strict';

  const PASSWORD='Demo@2026';
  const ACCOUNTS={
    CUSTOMER:{email:'customer.connected@sanpaid.demo',name:'Connected Demo Customer',label:'Customer Dashboard'},
    WORKER_A:{email:'worker1.connected@sanpaid.demo',name:'Amit Connected',label:'Worker Dashboard · A'},
    WORKER_B:{email:'worker2.connected@sanpaid.demo',name:'Suresh Connected',label:'Worker Dashboard · B'}
  };
  const STATUS_LABELS={
    REQUESTED:'Finding Verified Worker',VALIDATING:'Checking Eligibility',MATCHING:'Finding Verified Worker',OFFERING:'Waiting for Worker Response',PENDING_WORKER_ACCEPTANCE:'Waiting for Worker Response',FINDING_REPLACEMENT:'Finding Another Verified Worker',ASSIGNED:'Worker Assigned',ACCEPTED:'Worker Assigned',ON_THE_WAY:'Worker On The Way',TRAVELING:'Worker On The Way',ARRIVED:'Worker Arrived',IDENTITY_VERIFIED:'Worker Identity Verified',CUSTOMER_CONFIRMED:'Worker Confirmed',SERVICE_STARTED:'Service Started',IN_PROGRESS:'Service In Progress',AWAITING_CUSTOMER_CONFIRMATION:'Waiting for Completion Confirmation',COMPLETED:'Service Completed',PAYMENT_PENDING:'Payment Pending',PAID:'Payment Completed',CLOSED:'Closed',CANCELLED:'Cancelled',NO_WORKER_AVAILABLE:'No Eligible Worker Available'
  };
  let currentUser=null;
  let currentPersona=null;
  let stream=null;
  let activeBookingId=null;
  let voiceMeta={source:'TEXT',language:'mr',transcript:''};
  let lastCustomerSignature='';
  let lastWorkerSignature='';

  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function localDate(offsetDays=0){const d=new Date();d.setDate(d.getDate()+offsetDays);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
  function friendlyError(err,context='request'){
    const status=Number(err?.status||0);
    const raw=String(err?.message||'').toLowerCase();
    if(status===401)return 'Your demo session expired. Please log in again.';
    if(status===403)return 'This action is not available for this demo role.';
    if(status===404)return context==='booking'?'This booking is no longer available.':'The requested item could not be found.';
    if(status===409)return context==='offer'?'This job is no longer available. Refreshing your offers…':err?.message||'This action was already completed on another device.';
    if(status===422)return err?.message||'Please check the entered details.';
    if(status===429)return 'Too many requests. Please wait a moment and retry.';
    if(status>=500||/timeout|connect|unavailable|failed/.test(raw))return 'Service temporarily unavailable. Please retry.';
    return context==='booking'?'Booking could not be created. Please retry.':err?.message||'Something went wrong. Please retry.';
  }
  async function request(path,opt={}){
    const response=await fetch(path,{...opt,credentials:'include',headers:{'Content-Type':'application/json',...(opt.headers||{})},cache:'no-store'});
    const data=await response.json().catch(()=>({}));
    if(!response.ok){const e=new Error(data.message||data.error||`Request failed (${response.status})`);e.status=response.status;e.data=data;throw e;}
    return data;
  }
  const post=(path,body)=>request(path,{method:'POST',body:JSON.stringify(body||{})});
  const statusLabel=status=>STATUS_LABELS[String(status||'').toUpperCase()]||String(status||'').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());

  function shell(){
    let root=document.getElementById('connectedShell');
    if(root)return root;
    root=document.createElement('section');
    root.id='connectedShell';
    root.className='connected-shell hidden';
    root.setAttribute('aria-label','SanPaid connected service demo');
    root.innerHTML=`<header class="connected-top"><div><div class="brand">San<span>Paid</span></div><div id="connectedHeaderSubtitle" class="connected-top-subtitle">Connected service network</div></div><div class="actions"><span id="connectedTopStatus" class="connected-live">Checking…</span><button class="btn ghost small close-connected" id="connectedClose" aria-label="Close connected dashboard">✕</button></div></header><main class="connected-main" id="connectedContent"></main><div id="connectedModalRoot"></div>`;
    document.body.appendChild(root);
    root.querySelector('#connectedClose').onclick=close;
    return root;
  }
  function setHeaderSubtitle(text){const el=shell().querySelector('#connectedHeaderSubtitle');if(el&&el.textContent!==text)el.textContent=text;}
  function setLiveState(state){const el=shell().querySelector('#connectedTopStatus');if(!el)return;const map={online:['● Live','#8ee2b5'],checking:['Checking…','#b8c6d8'],offline:['● Offline','#ff9b9b'],retry:['● Reconnecting…','#ffb66e']};const [text,color]=map[state]||map.checking;if(el.textContent!==text)el.textContent=text;el.style.color=color;}

  async function open(persona=null){const root=shell();root.classList.remove('hidden');document.body.style.overflow='hidden';currentPersona=persona;setLiveState('checking');await checkHealth();try{const me=await request('/api/auth/me');currentUser=me.user||null;}catch{currentUser=null;}if(currentUser){renderApp();connectStream();}else renderChooser(persona);}
  function close(){shell().classList.add('hidden');document.body.style.overflow='';stopStream();closeDecisionModal();}
  async function checkHealth(){try{const h=await request('/api/connected/health');setLiveState(h.ok?'online':'offline');}catch{setLiveState('offline');}}

  function renderChooser(preselect=null){setHeaderSubtitle('Connected service network');const content=shell().querySelector('#connectedContent');content.dataset.connectedRole='';content.innerHTML=`<div class="connected-status"><span class="connected-badge">CONNECTED SIH WORKSPACE</span><span class="connected-live">Choose the role you want to demonstrate on this device</span></div><div class="connected-card connected-intro"><h2>Choose a role dashboard</h2><p>Customer and Worker dashboards share the same connected PostgreSQL service workflow while keeping role-specific actions simple.</p><div class="connected-demo-note">Isolated SIH demo accounts only. No real customer or worker data is used here.</div></div><div class="connected-grid">${roleCard('CUSTOMER','👤','Customer Dashboard','Book and track a verified local service.',ACCOUNTS.CUSTOMER.email)}${roleCard('WORKER_A','🛠','Worker Dashboard · A','Review the first eligible opportunity and choose Accept or Decline.',ACCOUNTS.WORKER_A.email)}${roleCard('WORKER_B','⚡','Worker Dashboard · B','Receive the same booking if the first worker declines.',ACCOUNTS.WORKER_B.email)}</div>`;content.querySelectorAll('[data-connected-persona]').forEach(btn=>btn.onclick=()=>renderLogin(btn.dataset.connectedPersona));if(preselect&&ACCOUNTS[preselect])setTimeout(()=>renderLogin(preselect),0);}
  function roleCard(id,icon,title,desc,email){return `<button class="connected-card connected-role" data-connected-persona="${id}"><h3>${icon} ${title}</h3><p>${desc}</p><div class="connected-account"><code>${email}</code></div><span class="btn primary small connected-role-cta">Open Dashboard</span></button>`;}

  function renderLogin(persona){currentPersona=persona;const account=ACCOUNTS[persona];const role=persona==='CUSTOMER'?'CUSTOMER':'WORKER';setHeaderSubtitle(account.label);const content=shell().querySelector('#connectedContent');content.dataset.connectedRole='';content.innerHTML=`<div class="connected-card connected-login-card"><button class="btn secondary small" id="connectedBack">← Roles</button><h2>${esc(account.label)}</h2><p>Sign in to this isolated SIH demo identity.</p><form id="connectedLogin" class="connected-form"><div class="field"><label>Email</label><input id="connectedEmail" type="email" value="${esc(account.email)}" required></div><div class="field"><label>Password</label><input id="connectedPassword" type="password" value="${PASSWORD}" required></div><div id="connectedLoginError"></div><button class="btn primary" type="submit" id="connectedLoginBtn">Continue to Dashboard</button></form><details class="connected-tech-details"><summary>Demo access details</summary><div class="connected-account">Role: <b>${role}</b><br>Demo password: <code>${PASSWORD}</code></div></details></div>`;content.querySelector('#connectedBack').onclick=()=>renderChooser();content.querySelector('#connectedLogin').onsubmit=async e=>{e.preventDefault();const error=content.querySelector('#connectedLoginError');const btn=content.querySelector('#connectedLoginBtn');error.innerHTML='';btn.disabled=true;btn.textContent='Signing in…';try{const result=await post('/api/auth/login',{identifier:content.querySelector('#connectedEmail').value.trim(),password:content.querySelector('#connectedPassword').value,role,remember:true});currentUser=result.user;renderApp();connectStream();}catch(err){error.innerHTML=`<div class="connected-error">${esc(friendlyError(err,'login'))}</div>`;btn.disabled=false;btn.textContent='Continue to Dashboard';}};}

  function renderApp(){if(!currentUser)return renderChooser();if(currentUser.role==='CUSTOMER')renderCustomer();else if(currentUser.role==='WORKER')renderWorker();else renderChooser();}
  function appHeader(title,subtitle){return `<div class="connected-status"><span class="connected-badge">SYNCED ACROSS DEVICES</span><span class="connected-live">${esc(currentUser.fullName||currentUser.email||'Connected User')}</span></div><div class="connected-card connected-app-heading"><div class="connected-heading-row"><div><h2>${title}</h2><p>${subtitle}</p></div><div class="connected-actions connected-header-actions"><button class="btn secondary small" id="connectedSwitch">Switch Role</button><button class="btn danger small" id="connectedLogout">Logout</button></div></div></div>`;}
  function wireHeader(){document.getElementById('connectedSwitch').onclick=async()=>{await logout();renderChooser();};document.getElementById('connectedLogout').onclick=async()=>{await logout();renderChooser();};}
  async function logout(){stopStream();try{await post('/api/auth/logout',{});}catch{}currentUser=null;activeBookingId=null;lastCustomerSignature='';lastWorkerSignature='';voiceMeta={source:'TEXT',language:'mr',transcript:''};}

  async function loadServiceCatalog(){const select=document.getElementById('cdService');if(!select)return;try{const data=await request('/api/connected/customer/services');const rows=data.services||[];const current=select.value;select.innerHTML=rows.map(s=>`<option value="${esc(s.name)}">${esc(s.name)} · from ₹${Number(s.basePrice||0).toLocaleString('en-IN')}</option>`).join('')||'<option>Electrician</option>';if(rows.some(s=>s.name===current))select.value=current;window.dispatchEvent(new CustomEvent('sanpaid:services-loaded',{detail:{services:rows}}));}catch{if(!select.options.length)select.innerHTML='<option>Electrician</option>';}}
  function renderCustomer(){setHeaderSubtitle('Customer Dashboard');const content=shell().querySelector('#connectedContent');content.dataset.connectedRole='CUSTOMER';lastCustomerSignature='';content.innerHTML=appHeader('Customer Dashboard','Book a verified local service and always see the next action clearly.')+`<div class="connected-grid connected-customer-grid"><div class="connected-card"><span class="connected-step-label">BOOK SERVICE</span><h3>Tell us what you need</h3><form id="connectedBookingForm" class="connected-form"><div class="field"><label>Service</label><select id="cdService" required><option>Loading services…</option></select></div><div class="connected-form-row"><div class="field"><label>Requested Date</label><input id="cdDate" type="date" value="${localDate(1)}" min="${localDate(0)}" required></div><div class="field"><label>Preferred Time</label><select id="cdTime"><option value="09:00">9 AM</option><option value="11:00">11 AM</option><option value="13:00">1 PM</option><option value="15:00">3 PM</option><option value="17:00">5 PM</option></select></div></div><div class="field"><label>Location / Area</label><input id="cdZone" value="Karad Zone 1" required></div><div class="field"><label>Service Address</label><input id="cdAddress" value="Demo Address, Karad Zone 1" required></div><div class="field"><label>Language</label><select id="cdLang"><option value="mr">Marathi</option><option value="hi">Hindi</option><option value="en">English</option></select></div><div class="field"><label>Describe the problem</label><textarea id="cdProblem" required placeholder="Describe the service request">Mala electrician pahije. Gharat switch board madhun spark yet aahe.</textarea></div><label class="connected-check"><input id="cdEmergency" type="checkbox"><span><b>Urgent service</b><small>Add the configured emergency charge and prioritize the request in this demo flow.</small></span></label><div class="connected-actions"><button type="button" class="btn secondary" id="cdVoice">🎙 Speak Request</button><button class="btn primary" type="submit" id="cdSubmit">Find Verified Worker</button></div><div id="cdVoiceStatus" class="connected-demo-note">Voice is optional. Review the captured text before sending.</div><div id="cdBookingProgress"></div><div id="cdBookingError"></div></form></div><div class="connected-card"><span class="connected-step-label">LIVE STATUS</span><h3>Your Service Request</h3><div id="connectedCustomerState" class="connected-booking-state"><div class="connected-empty"><b>No active booking</b><br>Book a verified local service to begin.</div></div></div></div>`;wireHeader();content.querySelector('#cdVoice').onclick=startCustomerVoice;content.querySelector('#connectedBookingForm').onsubmit=createConnectedBooking;loadServiceCatalog();loadLatestCustomerBooking();}
  function langCode(short){return short==='mr'?'mr-IN':short==='hi'?'hi-IN':'en-IN';}
  function startCustomerVoice(){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;const status=document.getElementById('cdVoiceStatus');const btn=document.getElementById('cdVoice');if(!Recognition){status.textContent='Microphone recognition is unavailable here. Type the request instead.';return;}const recognition=new Recognition();const lang=document.getElementById('cdLang').value;recognition.lang=langCode(lang);recognition.interimResults=false;recognition.maxAlternatives=1;btn.disabled=true;btn.textContent='Listening…';status.textContent='Listening… speak your complete service request.';recognition.onresult=e=>{const transcript=String(e.results?.[0]?.[0]?.transcript||'').trim();if(transcript){document.getElementById('cdProblem').value=transcript;voiceMeta={source:'VOICE',language:lang,transcript};status.textContent='Voice captured. Review the text, then find a verified worker.';}};recognition.onerror=()=>{status.textContent='Voice capture was not available. Text input still works.';};recognition.onend=()=>{btn.disabled=false;btn.textContent='🎙 Speak Request';};try{recognition.start();}catch{btn.disabled=false;btn.textContent='🎙 Speak Request';status.textContent='Microphone could not start. Type the request instead.';}}
  async function createConnectedBooking(e){e.preventDefault();const error=document.getElementById('cdBookingError');const progress=document.getElementById('cdBookingProgress');const btn=document.getElementById('cdSubmit');error.innerHTML='';const problem=document.getElementById('cdProblem').value.trim();const lang=document.getElementById('cdLang').value;const isVoice=voiceMeta.source==='VOICE'&&voiceMeta.transcript&&voiceMeta.transcript===problem;const date=document.getElementById('cdDate').value;const time=document.getElementById('cdTime').value;const scheduled=new Date(`${date}T${time}:00`);if(!date||!time||Number.isNaN(scheduled.getTime())||scheduled.getTime()<Date.now()-60000){error.innerHTML='<div class="connected-error">Choose a current or future service date and time.</div>';return;}btn.disabled=true;btn.textContent='Finding verified workers…';progress.innerHTML='<div class="connected-progress-note"><b>Checking worker eligibility</b><span>Identity · Skill · Availability · Required credentials · Service area</span></div>';try{const booking=await post('/api/connected/bookings',{service:document.getElementById('cdService').value,zone:document.getElementById('cdZone').value.trim(),address:document.getElementById('cdAddress').value.trim(),problem,requestSource:isVoice?'VOICE':'TEXT',requestLanguage:lang,voiceTranscript:isVoice?problem:null,scheduledAt:scheduled.toISOString(),emergency:document.getElementById('cdEmergency').checked});activeBookingId=booking.id;localStorage.setItem('sanpaid_connected_booking_id',String(booking.id));progress.innerHTML='<div class="connected-success">Request created. SanPaid is offering the same booking to eligible workers in order.</div>';renderCustomerState(booking,true);await refreshCustomerBooking();window.dispatchEvent(new CustomEvent('sanpaid:connected-sync',{detail:{bookingId:booking.id,source:'customer-booking'}}));}catch(err){error.innerHTML=`<div class="connected-error">${esc(friendlyError(err,'booking'))}</div>`;progress.innerHTML='';}finally{btn.disabled=false;btn.textContent='Find Verified Worker';}}
  async function loadLatestCustomerBooking(){const saved=Number(localStorage.getItem('sanpaid_connected_booking_id')||0);if(saved){activeBookingId=saved;await refreshCustomerBooking();}}
  async function refreshCustomerBooking(){if(!activeBookingId)return;try{const b=await request(`/api/connected/customer/bookings/${activeBookingId}`);renderCustomerState(b);}catch(err){if(err.status===404){localStorage.removeItem('sanpaid_connected_booking_id');activeBookingId=null;lastCustomerSignature='';}}}

  function bookingStep(status){const s=String(status||'').toUpperCase();if(['PAID','CLOSED'].includes(s))return 6;if(['COMPLETED','PAYMENT_PENDING','SERVICE_STARTED','IN_PROGRESS','AWAITING_CUSTOMER_CONFIRMATION'].includes(s))return 5;if(['IDENTITY_VERIFIED','CUSTOMER_CONFIRMED'].includes(s))return 4;if(s==='ARRIVED')return 3;if(['ASSIGNED','ACCEPTED','ON_THE_WAY','TRAVELING'].includes(s))return 2;if(['OFFERING','PENDING_WORKER_ACCEPTANCE','FINDING_REPLACEMENT','NO_WORKER_AVAILABLE'].includes(s))return 1;return 0;}
  function stepper(status){const current=bookingStep(status);const labels=['Request','Worker Match','Accepted','Arrival','Verification','Service','Payment'];return `<div class="connected-stepper">${labels.map((label,i)=>`<div class="connected-step ${i<current?'done':i===current?'active':''}"><span>${i<current?'✓':i+1}</span><small>${label}</small></div>`).join('')}</div>`;}
  function customerSignature(b){return JSON.stringify([b.id,b.status,b.workerName,b.workerVerification,b.distance,b.cooperative,b.voiceTranscript,b.requestSource,b.scheduledAt,b.emergency,b.updatedAt]);}
  function renderCustomerState(b,force=false){const root=document.getElementById('connectedCustomerState');if(!root)return;const signature=customerSignature(b);if(!force&&signature===lastCustomerSignature)return;lastCustomerSignature=signature;const status=String(b.status||'');const replacement=status==='FINDING_REPLACEMENT';const assigned=!!b.workerName;root.innerHTML=`${stepper(status)}<div class="connected-success connected-request-summary"><div><small>Booking ID</small><b>${esc(b.bookingCode||'Booking created')}</b></div><span class="badge ${replacement?'b-orange':'b-green'}">${esc(statusLabel(status))}</span></div><div class="connected-state-line"><b>${replacement?'Finding another verified worker…':'Current status'}</b><p>${replacement?'The first worker declined or became unavailable. The same booking is being offered to the next eligible worker.':esc(statusLabel(status))}</p></div><div class="connected-state-line"><div class="connected-summary-grid"><div><small>Service</small><b>${esc(b.service||'Service')}</b></div><div><small>Request</small><b>${esc(b.requestSource==='VOICE'?'Voice':'Text')}</b></div><div><small>Scheduled</small><b>${b.scheduledAt?esc(new Date(b.scheduledAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})):'—'}</b></div><div><small>Urgency</small><b>${b.emergency?'Urgent':'Standard'}</b></div></div></div>${assigned?`<div class="connected-state-line connected-worker-assigned"><span class="connected-step-label">ASSIGNED WORKER</span><h4>${esc(b.workerName)}</h4><p>${esc(b.workerVerification||'VERIFIED')} · ${b.distance!=null?`${esc(b.distance)} KM · `:''}${esc(b.cooperative||'Cooperative')}</p></div>`:`<div class="connected-state-line"><b>${replacement?'Replacement search active':'Waiting for worker response'}</b><p>No worker is shown as assigned until that worker accepts your request.</p></div>`}${b.voiceTranscript?`<div class="connected-voice"><b>🎙 Your Voice Request</b><div class="transcript">“${esc(b.voiceTranscript)}”</div></div>`:''}`;}

  function renderWorker(){setHeaderSubtitle('Worker Dashboard');const content=shell().querySelector('#connectedContent');content.dataset.connectedRole='WORKER';lastWorkerSignature='';content.innerHTML=appHeader('Worker Dashboard','Review suitable opportunities, choose work and follow one trusted service workflow.')+`<div class="connected-card"><div class="connected-heading-row"><div><span class="connected-step-label">JOB REQUESTS</span><h3>Available Work</h3><p>New opportunities appear only after eligibility checks. Accept or Decline remains your choice.</p></div><button class="btn secondary small" id="connectedRefreshOffers">Refresh</button></div><div id="connectedWorkerMessage"></div><div id="connectedWorkerOffers" class="connected-list"><div class="connected-empty">Loading job offers…</div></div></div>`;wireHeader();content.querySelector('#connectedRefreshOffers').onclick=()=>loadWorkerOffers(true);loadWorkerOffers(true);}
  function workerOffersSignature(offers){return JSON.stringify((offers||[]).map(o=>[o.offerId,o.offerStatus,o.status,o.bookingId,o.distance,o.total,o.scheduledAt,o.voiceTranscript,o.requestLanguage,o.workerLanguage]));}
  async function loadWorkerOffers(force=false){const root=document.getElementById('connectedWorkerOffers');if(!root)return;try{const offers=await request('/api/connected/worker/offers');const signature=workerOffersSignature(offers);if(!force&&signature===lastWorkerSignature)return;lastWorkerSignature=signature;root.innerHTML=offers.length?offers.map(offerCard).join(''):'<div class="connected-empty"><b>No job requests right now</b><br>Stay available. Suitable opportunities will appear here.</div>';wireOfferActions();}catch(err){root.innerHTML=`<div class="connected-error">${esc(friendlyError(err,'offer'))}</div>`;}}
  function offerCard(o){const lang=o.workerLanguage||'hi';const summary=workerSummary(o,lang);const accepted=o.offerStatus==='ACCEPTED';return `<article class="connected-offer" data-offer="${o.offerId}"><div class="connected-offer-head"><div><span class="badge ${accepted?'b-green':'b-orange'}">${accepted?'ACCEPTED':'NEW JOB REQUEST'}</span><h4>${esc(o.service)}</h4><p>${esc(o.zone||'Customer area')} · ${o.distance!=null?`${esc(o.distance)} KM away`:''}</p></div><div class="connected-earnings"><small>Expected Amount</small><b>₹${Number(o.total||0).toLocaleString('en-IN')}</b></div></div><div class="connected-meta"><div>Schedule<b>${o.scheduledAt?new Date(o.scheduledAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—'}</b></div><div>Cooperative<b>${esc(o.cooperative||'—')}</b></div><div>Booking ID<b>${esc(o.bookingCode||'—')}</b></div><div>Distance<b>${o.distance!=null?`${esc(o.distance)} KM`:'—'}</b></div></div>${o.voiceTranscript?`<div class="connected-voice"><span class="connected-step-label">CUSTOMER REQUEST</span><b>${esc(languageName(o.requestLanguage||'mr'))} Voice Request</b><div class="transcript"><strong>Worker Summary:</strong><br>${esc(summary)}</div><details><summary>Show Original Customer Request</summary><div class="transcript">“${esc(o.voiceTranscript)}”</div></details><div class="connected-actions"><button class="btn secondary small" data-listen-offer="${o.offerId}">🔊 Listen Summary</button><button class="btn secondary small" data-listen-original="${o.offerId}">▶ Listen Original</button></div></div>`:`<div class="connected-state-line"><b>Customer Request</b><p>${esc(o.problem||'No description')}</p></div>`}${o.offerStatus==='PENDING'?`<div class="connected-actions connected-offer-actions"><button class="btn danger" data-reject-offer="${o.offerId}">Decline</button><button class="btn primary" data-accept-offer="${o.offerId}">Accept Job</button></div>`:'<div class="connected-success">Job accepted. This booking is assigned to you.</div>'}</article>`;}
  function languageName(lang){const s=String(lang||'').toLowerCase();return s.startsWith('mr')?'Marathi':s.startsWith('hi')?'Hindi':'English';}
  function workerSummary(o,lang){if(String(lang).startsWith('mr'))return `तुम्हाला ${o.service} साठी जॉब रिक्वेस्ट मिळाली आहे. परिसर: ${o.zone||'ग्राहक परिसर'}. मूळ ग्राहक विनंती खाली उपलब्ध आहे.`;if(String(lang).startsWith('hi'))return `आपको ${o.service} की जॉब रिक्वेस्ट मिली है। क्षेत्र: ${o.zone||'ग्राहक क्षेत्र'}। ग्राहक की मूल रिक्वेस्ट नीचे उपलब्ध है।`;return `You have a ${o.service} job request in ${o.zone||'the customer area'}. The customer's original request is available below.`;}
  function speak(text,lang){if(!('speechSynthesis'in window)||!window.SpeechSynthesisUtterance)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=langCode(String(lang||'hi').slice(0,2));u.rate=.95;window.speechSynthesis.speak(u);}

  function wireOfferActions(){document.querySelectorAll('[data-accept-offer]').forEach(b=>b.onclick=()=>respondOffer(b,'ACCEPT'));document.querySelectorAll('[data-reject-offer]').forEach(b=>b.onclick=()=>openDecisionModal(b));document.querySelectorAll('[data-listen-offer]').forEach(b=>b.onclick=()=>{const card=b.closest('[data-offer]');const transcript=card?.querySelector('.connected-voice > .transcript')?.textContent?.replace(/^Worker Summary:\s*/i,'')||'';speak(transcript,currentUser?.preferredLanguage||'hi');});document.querySelectorAll('[data-listen-original]').forEach(b=>b.onclick=()=>{const card=b.closest('[data-offer]');const original=card?.querySelector('details .transcript')?.textContent?.replace(/[“”]/g,'')||'';const details=card?.querySelector('details summary')?.textContent||'';const lang=/Marathi/i.test(details)?'mr':/Hindi/i.test(details)?'hi':'en';speak(original,lang);});}
  function openDecisionModal(button){const id=button.dataset.rejectOffer;const root=document.getElementById('connectedModalRoot');root.innerHTML=`<div class="connected-modal-backdrop" role="presentation"><div class="connected-modal" role="dialog" aria-modal="true" aria-labelledby="declineTitle"><h3 id="declineTitle">Why are you declining this job?</h3><p>Your reason is recorded for cooperative operations. The customer request continues to the next eligible worker without forcing this opportunity on you.</p><div class="connected-choice-list">${['Schedule Conflict','Too Far','Unavailable','Not My Skill','Personal Reason','Other'].map((r,i)=>`<label><input type="radio" name="declineReason" value="${r}" ${i===0?'checked':''}><span>${r}</span></label>`).join('')}</div><div class="connected-actions"><button class="btn secondary" data-modal-cancel>Cancel</button><button class="btn danger" data-modal-confirm data-offer-id="${id}">Decline Job</button></div></div></div>`;root.querySelector('[data-modal-cancel]').onclick=closeDecisionModal;root.querySelector('[data-modal-confirm]').onclick=()=>{const reason=root.querySelector('input[name="declineReason"]:checked')?.value||'Other';closeDecisionModal();respondOffer(button,'REJECT',reason);};}
  function closeDecisionModal(){const root=document.getElementById('connectedModalRoot');if(root)root.innerHTML='';}
  function workerMessage(text,type='success'){const el=document.getElementById('connectedWorkerMessage');if(el)el.innerHTML=`<div class="${type==='error'?'connected-error':type==='warn'?'connected-demo-note':'connected-success'}">${esc(text)}</div>`;}
  async function respondOffer(button,action,reason=''){if(button.disabled)return;const id=button.dataset.acceptOffer||button.dataset.rejectOffer;const old=button.textContent;button.disabled=true;button.textContent=action==='ACCEPT'?'Accepting Job…':'Declining Job…';try{const result=await post(`/api/connected/worker/offers/${id}/respond`,{action,reason});lastWorkerSignature='';await loadWorkerOffers(true);if(action==='REJECT'){workerMessage(result.nextWorker?'Job declined. The same booking is moving to the next eligible worker.':'Job declined. No penalty is applied in this demo workflow.','warn');}else workerMessage('Job accepted. The customer has been notified.');window.dispatchEvent(new CustomEvent('sanpaid:connected-sync',{detail:{source:'worker-offer',action}}));}catch(err){workerMessage(friendlyError(err,'offer'),'error');button.disabled=false;button.textContent=old;lastWorkerSignature='';await loadWorkerOffers(true);}}

  function connectStream(){stopStream();if(!window.EventSource)return;stream=new EventSource('/api/connected/events',{withCredentials:true});stream.addEventListener('snapshot',event=>{try{const snapshot=JSON.parse(event.data);if(snapshot.role==='CUSTOMER'){const latest=snapshot.bookings?.[0];if(latest&&(!activeBookingId||Number(latest.id)===Number(activeBookingId))){activeBookingId=Number(latest.id);localStorage.setItem('sanpaid_connected_booking_id',String(activeBookingId));refreshCustomerBooking();}}else if(snapshot.role==='WORKER'){loadWorkerOffers();}}catch{}});stream.onerror=()=>setLiveState('retry');stream.onopen=()=>setLiveState('online');}
  function stopStream(){if(stream){stream.close();stream=null;}}

  function installLandingButtons(){const ctas=document.querySelector('.hero-ctas');if(ctas&&!document.getElementById('connectedDemoBtn')){const btn=document.createElement('button');btn.className='btn secondary';btn.id='connectedDemoBtn';btn.type='button';btn.textContent='▶ Open Connected Prototype';btn.onclick=()=>open();ctas.appendChild(btn);}const match=document.getElementById('matching');if(match&&!document.getElementById('connectedDemoSection')){const sec=document.createElement('section');sec.id='connectedDemoSection';sec.className='section white';sec.innerHTML=`<div class="wrap"><div class="head"><span class="tag">Working Cross-Device Proof</span><h2>One request. Multiple devices. One connected workflow.</h2><p>See the customer request move from eligibility-first matching to Worker A, then to Worker B if the first worker declines.</p></div><div class="connected-grid"><div class="connected-card"><h3>1 · Customer</h3><p>Book a verified local service using Marathi, Hindi or English voice/text.</p><button class="btn primary" data-open-connected="CUSTOMER">Open Customer Dashboard</button></div><div class="connected-card"><h3>2 · Worker A</h3><p>Receive the first eligible opportunity and choose Accept or Decline.</p><button class="btn secondary" data-open-connected="WORKER_A">Open Worker A</button></div><div class="connected-card"><h3>3 · Worker B</h3><p>Receive the same booking if Worker A declines.</p><button class="btn secondary" data-open-connected="WORKER_B">Open Worker B</button></div></div><details class="connected-tech-details"><summary>Technical proof</summary><p>These demo identities share the same backend workflow and PostgreSQL state; cross-device job delivery does not depend on customer-device localStorage.</p></details></div>`;match.insertAdjacentElement('afterend',sec);sec.querySelectorAll('[data-open-connected]').forEach(b=>b.onclick=()=>open(b.dataset.openConnected));}}

  window.ConnectedSanPaid={open,close,refreshCustomerBooking,loadWorkerOffers,reloadServices:loadServiceCatalog};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installLandingButtons,{once:true});else installLandingButtons();
})();
