(() => {
  'use strict';

  const TOKEN_KEY='sanpaid_judge_demo_token_v1';
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const human=v=>String(v||'—').replaceAll('_',' ').toLowerCase().replace(/\b\w/g,m=>m.toUpperCase());
  const fmtDate=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});};
  const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;

  let workspace=null;
  let refreshPromise=null;
  let returnFocus=null;
  let observer=null;
  let timer=0;

  function currentRole(){return String(window.SanPaidAuth?.getRole?.()||document.querySelector('#sihJudgeShell')?.dataset?.adminRole||'').toUpperCase();}
  function isCooperative(){const shell=$('#sihJudgeShell');return !!shell&&!shell.classList.contains('judge-hidden')&&currentRole()==='COOPERATIVE_ADMIN';}
  function token(){try{return sessionStorage.getItem(TOKEN_KEY)||''}catch{return ''}}
  async function api(path,opt={}){
    const headers=new Headers(opt.headers||{});const t=token();if(t)headers.set('Authorization',`Bearer ${t}`);if(opt.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');
    const r=await fetch(path,{...opt,credentials:'include',cache:'no-store',headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(data.message||data.error||`Request failed (${r.status})`),{status:r.status,data});return data;
  }
  const post=(path,body)=>api(path,{method:'POST',body:JSON.stringify(body||{})});
  function badge(value,tone){const text=human(value),t=tone||(/VERIFIED|BALANCED|PAID|COMPLETED|AVAILABLE|CONNECTED|READY/.test(String(value))?'ok':/BREACH|EXPIRED|SUSPENDED|INACTIVE|LOW/.test(String(value))?'risk':/PENDING|MONITOR|REQUESTED|RECOMMENDED|WAITING/.test(String(value))?'warn':'neutral');return `<span class="coop-status ${t}">${esc(text)}</span>`;}
  function switchTo(id){window.SanPaidJudgeMode?.switchTab?.(id);setActiveNav(id);setTimeout(()=>$('#sihJudgeShell .judge-section.active')?.scrollIntoView({behavior:'smooth',block:'start'}),50);closeNav();}
  function scrollToId(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});setActiveNav(id);closeNav();}
  function setActiveNav(target){$$('#coopSidebar [data-coop-target]').forEach(b=>b.classList.toggle('active',b.dataset.coopTarget===target));}
  function closeNav(){const c=$('#judgeContent');if(c)c.classList.remove('coop-nav-open');$('#coopNavToggle')?.setAttribute('aria-expanded','false');}

  const NAV=[
    ['coop-home','Overview','Local society operations'],
    ['coop-workers','Workers','Directory and availability'],
    ['coop-verification','Verification Queue','Identity review and documents'],
    ['coop-skills','Skills & Documents','Eligibility evidence'],
    ['coop-services','Bookings & Services','Active service operations'],
    ['matching','Matching & Allocation','Eligibility-first proof'],
    ['coop-complaints','Complaints & SLA','Local grievance oversight'],
    ['coop-capacity','Local Capacity','Demand and workforce gaps'],
    ['coop-quality','Service Quality','Ratings and outcomes'],
    ['coop-payments','Payments & Earnings','Recorded transaction visibility'],
    ['planning','Demand & Planning','Advisory planning'],
    ['coop-training','Training & Development','Human-approved recommendations'],
    ['welfare','Welfare Readiness','Worker support roadmap'],
    ['coop-activity','Audit & Activity','Traceable local operations'],
    ['coop-health','System Health','Read-only runtime checks'],
    ['golden','System Proof','Golden Demo and evidence'],
    ['research','Architecture & Research','Technical evidence']
  ];

  function ensureFrame(){
    const shell=$('#sihJudgeShell'),content=$('#judgeContent');if(!shell||!content)return;
    shell.classList.add('cooperative-govtech');shell.classList.remove('federation-govtech');
    const topSmall=$('.judge-top small',shell);if(topSmall)topSmall.textContent='Cooperative Operations Prototype · Local Society Operations Workspace';
    const hero=$('.judge-hero',content);if(hero){const b=$('.judge-badge',hero),h=$('h1',hero),p=$('p',hero);if(b)b.textContent='COOPERATIVE OPERATIONS · SIH 2026';if(h)h.textContent='Cooperative Operations Command Center';if(p)p.textContent='Local workforce, service delivery, verification, complaints and capacity management in one governed workspace.';if(!$('#coopGovTruth',hero)){const x=document.createElement('small');x.id='coopGovTruth';x.className='coop-gov-truth';x.textContent='GovTech-inspired cooperative operations prototype · Not an official government portal';p?.insertAdjacentElement('afterend',x);}}
    const heading=$('#adminCommandSummary .admin-command-heading');if(heading){const h2=$('h2',heading),p=$('p',heading),btn=$('#adminHealthRefresh',heading);if(h2)h2.textContent='What needs attention now?';if(p)p.textContent='Local operational priorities are derived from the authenticated cooperative scope. Read refreshes never mutate demo state.';if(btn)btn.textContent='Refresh Local Data';}
    if(!$('#coopSidebar',content)){
      const aside=document.createElement('aside');aside.id='coopSidebar';aside.className='coop-sidebar';aside.setAttribute('aria-label','Cooperative operations navigation');aside.innerHTML=`<div class="coop-side-brand"><b>SanPaid</b><span>COOPERATIVE OPERATIONS</span><small>Cooperative Workforce Network</small></div><nav><span class="coop-nav-group">Operations</span>${NAV.map(([target,label,desc],i)=>`${i===14?'<span class="coop-nav-group system">System</span>':''}<button type="button" data-coop-target="${esc(target)}"><span>${esc(label)}</span><small>${esc(desc)}</small></button>`).join('')}</nav><div class="coop-side-foot"><span>Cooperative Operations Prototype · SIH 2026</span><small>Local society scope · GovTech-inspired</small></div>`;content.insertBefore(aside,content.firstChild);
      aside.querySelectorAll('[data-coop-target]').forEach(btn=>btn.addEventListener('click',()=>btn.dataset.coopTarget.startsWith('coop-')?scrollToId(btn.dataset.coopTarget):switchTo(btn.dataset.coopTarget)));
      const toggle=document.createElement('button');toggle.id='coopNavToggle';toggle.className='coop-nav-toggle';toggle.type='button';toggle.setAttribute('aria-controls','coopSidebar');toggle.setAttribute('aria-expanded','false');toggle.textContent='Cooperative Menu';content.insertBefore(toggle,aside.nextSibling);toggle.addEventListener('click',()=>{const open=content.classList.toggle('coop-nav-open');toggle.setAttribute('aria-expanded',String(open));});
    }
    ensureProfile();setActiveNav('coop-home');
  }

  function ensureProfile(){const actions=$('#sihJudgeShell .judge-top-actions');if(!actions||$('#coopProfileChip',actions))return;const u=window.SanPaidAuth?.getCurrentUser?.()||{};const chip=document.createElement('div');chip.id='coopProfileChip';chip.className='coop-profile-chip';chip.innerHTML=`<span>${esc(u.full_name||u.fullName||u.name||'Cooperative Admin')}</span><small>${esc(u.email||'COOPERATIVE_ADMIN')}</small>`;actions.insertBefore(chip,$('#judgeClose',actions)||null);if(!$('#coopLastSync',actions)){const sync=document.createElement('span');sync.id='coopLastSync';sync.className='coop-last-sync';sync.textContent='Last sync —';actions.insertBefore(sync,chip);}}

  function ensurePortal(){
    const summary=$('#adminCommandSummary');if(!summary)return null;let root=$('#coopPortal',summary);if(root)return root;root=document.createElement('div');root.id='coopPortal';root.className='coop-portal';root.innerHTML=`
      <section id="coop-home" class="coop-section"><div class="coop-section-head"><div><span>LOCAL SOCIETY OPERATIONS</span><h3 id="coopTitle">Cooperative overview</h3></div><small id="coopScopeLabel">Authenticated cooperative scope</small></div><div id="coopKpis" class="coop-kpi-grid"><div class="admin-skeleton">Loading workforce overview…</div></div><div id="coopToday" class="coop-today"><div class="admin-skeleton">Loading today's operations…</div></div></section>
      <section id="coop-workers" class="coop-section"><div class="coop-section-head"><div><span>WORKFORCE</span><h3>Worker Directory</h3></div><small>Local cooperative workers only</small></div><div id="coopWorkerTable"><div class="admin-skeleton">Loading workers…</div></div></section>
      <section id="coop-verification" class="coop-section"><div class="coop-section-head"><div><span>TRUST GOVERNANCE</span><h3>Verification Queue</h3></div><small>Authorized cooperative review</small></div><div id="coopVerification"><div class="admin-skeleton">Checking verification queue…</div></div></section>
      <section id="coop-skills" class="coop-section"><div class="coop-section-head"><div><span>ELIGIBILITY EVIDENCE</span><h3>Skills & Document Readiness</h3></div><small>Skill verification remains independent</small></div><div id="coopSkills"><div class="admin-skeleton">Loading skills…</div></div></section>
      <section id="coop-services" class="coop-section"><div class="coop-section-head"><div><span>SERVICE OPERATIONS</span><h3>Bookings & Active Services</h3></div><small>Customer-safe operational view</small></div><div id="coopServices"><div class="admin-skeleton">Loading active services…</div></div></section>
      <section id="coop-complaints" class="coop-section"><div class="coop-section-head"><div><span>GRIEVANCE MANAGEMENT</span><h3>Complaints & SLA</h3></div><small>L1 / L2 local visibility · L3 Federation escalation</small></div><div id="coopComplaints"><div class="admin-skeleton">Loading complaints…</div></div></section>
      <section id="coop-capacity" class="coop-section"><div class="coop-section-head"><div><span>LOCAL CAPACITY</span><h3>Demand & Workforce Capacity</h3></div><small>Observed local demand · Human-controlled action</small></div><div id="coopCapacity"><div class="admin-skeleton">Calculating local capacity…</div></div></section>
      <section id="coop-quality" class="coop-section"><div class="coop-section-head"><div><span>SERVICE OUTCOMES</span><h3>Service Quality</h3></div><small>Stored outcomes only · No invented NPS</small></div><div id="coopQuality"></div></section>
      <section id="coop-payments" class="coop-section"><div class="coop-section-head"><div><span>FINANCIAL VISIBILITY</span><h3>Payments & Earnings Records</h3></div><small>Read-only admin oversight</small></div><div id="coopPayments"><div class="admin-skeleton">Loading payment records…</div></div></section>
      <section id="coop-training" class="coop-section"><div class="coop-section-head"><div><span>WORKFORCE DEVELOPMENT</span><h3>Training Recommendations</h3></div><small>Advisory · Human approval required</small></div><div id="coopTraining"></div></section>
      <section id="coop-activity" class="coop-section"><div class="coop-section-head"><div><span>AUDITABILITY</span><h3>Recent Operational Activity</h3></div><small>Connected records only</small></div><div id="coopActivity"></div></section>
      <section id="coop-readiness" class="coop-section"><div class="coop-section-head"><div><span>SOCIETY ADMINISTRATION READINESS</span><h3>Current platform vs future administrative integration</h3></div><small>No fake statutory records</small></div><div class="coop-readiness-grid"><article><span>Society Profile & Workforce Operations</span><b>Connected</b><p>Current SanPaid cooperative scope, workforce and service operations are database-backed.</p></article><article><span>Statutory Audit / Mandatory Returns</span><b>Future Administrative Integration</b><p>No fake annual returns, statutory audit certificates or filing status are generated.</p></article><article><span>Election / Inspection Records</span><b>Future Administrative Integration</b><p>Can be integrated only with an authorized administrative workflow and source.</p></article><article><span>Insurance / ESIC / Government Schemes</span><b>Future Authorized Integration</b><p>No live government scheme connection is claimed.</p></article></div></section>
      <section id="coop-health" class="coop-section"><div class="coop-section-head"><div><span>SYSTEM HEALTH</span><h3>Cooperative Feature Verification</h3></div><small>Frontend → API → Database → Authorization</small></div><div id="coopFeatureMatrix"><div class="admin-skeleton">Checking local workspace…</div></div></section>`;
    const lower=$('.admin-command-lower',summary);summary.insertBefore(root,lower||null);return root;
  }

  function renderAttention(d){const root=$('#adminAttentionGrid');if(!root)return;const m=d.metrics||{};const items=[['Pending Verification',m.pendingVerification,'Workers need authorized identity review.','coop-verification',m.pendingVerification?'warn':'ok'],['Document Issues',m.documentIssues,'Pending or expired required document evidence.','coop-skills',m.documentIssues?'warn':'ok'],['Open Complaints',m.openComplaints,'Local grievances requiring follow-up.','coop-complaints',m.openComplaints?'warn':'ok'],['SLA Breaches',m.slaBreaches,'Breached cases require escalation attention.','coop-complaints',m.slaBreaches?'risk':'ok'],['Unanswered Offers',m.pendingOffers,'Worker opportunities still awaiting response.','coop-services',m.pendingOffers?'info':'ok'],['Capacity Requests',m.capacityRequests,'Local or provider capacity coordination records.','coop-capacity',m.capacityRequests?'info':'ok']];root.innerHTML=items.map(([label,value,detail,target,tone])=>`<button type="button" class="admin-attention-card ${tone}" data-coop-attention="${target}"><span>${esc(label)}</span><strong>${Number(value||0)}</strong><small>${esc(detail)}</small><i>Review →</i></button>`).join('');root.querySelectorAll('[data-coop-attention]').forEach(b=>b.onclick=()=>scrollToId(b.dataset.coopAttention));}

  function renderKpis(d){const m=d.metrics||{},c=d.cooperative||{};$('#coopTitle').textContent=c.name||'Cooperative overview';$('#coopScopeLabel').textContent=[c.city,'Local cooperative scope'].filter(Boolean).join(' · ');const root=$('#coopKpis');root.innerHTML=[['Total Workers',m.totalWorkers,'Registered in this cooperative'],['Verified Workers',m.verifiedWorkers,'Identity verification completed'],['Available Workers',m.availableWorkers,'Verified + currently available'],['Active Services',m.activeBookings,'Current assigned services'],['Open Complaints',m.openComplaints,'Unresolved local grievances'],['Recorded Payments',money(m.recordedPayments),'Recorded ledger visibility']].map(([l,v,d])=>`<article class="coop-kpi"><span>${esc(l)}</span><strong>${esc(v)}</strong><small>${esc(d)}</small></article>`).join('');}

  function renderToday(d){const rows=d.services||[],states=[['Waiting for Worker',rows.filter(x=>x.status==='PENDING_WORKER_ACCEPTANCE').length],['On The Way',rows.filter(x=>['ON_THE_WAY','TRAVELING','WORKER_ON_THE_WAY'].includes(x.status)).length],['Arrived',rows.filter(x=>x.status==='ARRIVED').length],['In Progress',rows.filter(x=>x.status==='IN_PROGRESS').length],['Awaiting Completion',rows.filter(x=>['AWAITING_CUSTOMER_CONFIRMATION','COMPLETION_REQUESTED'].includes(x.status)).length],['Completed',rows.filter(x=>['COMPLETED','PAID'].includes(x.status)).length]];$('#coopToday').innerHTML=`<div class="coop-mini-head"><b>Today's Operations</b><span>Current local service states</span></div><div class="coop-today-grid">${states.map(([l,v])=>`<article><strong>${v}</strong><span>${esc(l)}</span></article>`).join('')}</div>`;}

  function workerSkillText(w){return (w.skills||[]).map(s=>s.service).filter(Boolean).join(', ')||'—';}
  function renderWorkers(d){const workers=d.workers||[],root=$('#coopWorkerTable');const skills=[...new Set(workers.flatMap(w=>(w.skills||[]).map(s=>s.service)).filter(Boolean))].sort();const ver=[...new Set(workers.map(w=>w.verificationStatus).filter(Boolean))].sort();const avail=[...new Set(workers.map(w=>w.availability).filter(Boolean))].sort();root.innerHTML=`<div class="coop-toolbar"><label><span>Search Worker</span><input id="coopWorkerSearch" type="search" placeholder="Name or skill"></label><label><span>Skill</span><select id="coopSkillFilter"><option value="">All skills</option>${skills.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label><span>Verification</span><select id="coopVerifyFilter"><option value="">All states</option>${ver.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label><span>Availability</span><select id="coopAvailFilter"><option value="">All states</option>${avail.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><button type="button" class="btn secondary small" id="coopWorkerReset">Reset</button><span id="coopWorkerCount" class="coop-count" aria-live="polite"></span></div><div class="judge-table-wrap"><table class="judge-table coop-table"><thead><tr><th>Worker</th><th>Skill</th><th>Verification</th><th>Availability</th><th>Jobs</th><th>Rating</th><th>Documents</th><th>Action</th></tr></thead><tbody>${workers.map(w=>`<tr data-worker-row data-name="${esc(String(w.name||'').toLowerCase())}" data-skill="${esc(workerSkillText(w).toLowerCase())}" data-ver="${esc(w.verificationStatus||'')}" data-avail="${esc(w.availability||'')}"><td><b>${esc(w.name)}</b><small>#${Number(w.id)}</small></td><td>${esc(workerSkillText(w))}</td><td>${badge(w.verificationStatus)}</td><td>${badge(w.availability)}</td><td>${Number(w.jobsCompleted||0)}</td><td>${Number(w.rating||0).toFixed(1)}</td><td>${Number(w.pendingDocuments||0)+Number(w.expiredDocuments||0)?badge('Attention','warn'):badge('Ready','ok')}</td><td><button type="button" class="coop-table-action" data-worker-view="${Number(w.id)}">View Worker</button></td></tr>`).join('')}</tbody></table></div>`;
    const apply=()=>{const q=String($('#coopWorkerSearch')?.value||'').trim().toLowerCase(),skill=String($('#coopSkillFilter')?.value||'').toLowerCase(),v=$('#coopVerifyFilter')?.value||'',a=$('#coopAvailFilter')?.value||'';let shown=0;$$('[data-worker-row]',root).forEach(r=>{const ok=(!q||(r.dataset.name.includes(q)||r.dataset.skill.includes(q)))&&(!skill||r.dataset.skill.includes(skill))&&(!v||r.dataset.ver===v)&&(!a||r.dataset.avail===a);r.hidden=!ok;if(ok)shown++;});$('#coopWorkerCount').textContent=`Showing ${shown} of ${workers.length} workers`;};root.querySelectorAll('input,select').forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',apply));$('#coopWorkerReset')?.addEventListener('click',()=>{['#coopWorkerSearch','#coopSkillFilter','#coopVerifyFilter','#coopAvailFilter'].forEach(s=>{const e=$(s);if(e)e.value='';});apply();$('#coopWorkerSearch')?.focus();});root.querySelectorAll('[data-worker-view]').forEach(b=>b.addEventListener('click',()=>openWorker(Number(b.dataset.workerView),b)));apply();}

  function renderVerification(d){const pending=(d.workers||[]).filter(w=>String(w.verificationStatus||'')!=='VERIFIED'||Number(w.pendingDocuments||0)>0||Number(w.expiredDocuments||0)>0),root=$('#coopVerification');if(!pending.length){root.innerHTML='<div class="coop-empty">No workers currently require verification attention.</div>';return;}root.innerHTML=`<div class="judge-table-wrap"><table class="judge-table coop-table"><thead><tr><th>Worker</th><th>Identity</th><th>Skill Evidence</th><th>Document Issues</th><th>Action</th></tr></thead><tbody>${pending.map(w=>`<tr><td><b>${esc(w.name)}</b><small>#${Number(w.id)}</small></td><td>${badge(w.verificationStatus)}</td><td>${(w.skills||[]).map(s=>`${esc(s.service)} ${s.verified?badge('Verified','ok'):badge('Pending','warn')}`).join('<br>')||'—'}</td><td>${Number(w.pendingDocuments||0)} pending · ${Number(w.expiredDocuments||0)} expired</td><td><button type="button" class="coop-table-action" data-worker-view="${Number(w.id)}">Review Worker</button></td></tr>`).join('')}</tbody></table></div>`;root.querySelectorAll('[data-worker-view]').forEach(b=>b.addEventListener('click',()=>openWorker(Number(b.dataset.workerView),b)));}

  function renderSkills(d){const rows=d.skills||[],root=$('#coopSkills');if(!rows.length){root.innerHTML='<div class="coop-empty">No skill capacity records are available for this cooperative.</div>';return;}root.innerHTML=`<div class="judge-table-wrap"><table class="judge-table coop-table"><thead><tr><th>Service / Skill</th><th>Verified Workers</th><th>Available Workers</th><th>Observed Demand · 30d</th><th>Gap</th><th>Status</th></tr></thead><tbody>${rows.map(x=>{const gap=Number(x.demand30d||0)-Number(x.availableWorkers||0),status=gap>0?'CAPACITY LOW':Number(x.availableWorkers||0)===0?'MONITOR':'BALANCED';return `<tr><td><b>${esc(x.service)}</b></td><td>${Number(x.verifiedWorkers||0)}</td><td>${Number(x.availableWorkers||0)}</td><td>${Number(x.demand30d||0)}</td><td>${gap}</td><td>${badge(status)}</td></tr>`;}).join('')}</tbody></table></div><p class="coop-note">Document issue counts come from required verification/expiry evidence. Individual sensitive document contents are not exposed in this operations view.</p>`;}

  function renderServices(d){const rows=d.services||[],root=$('#coopServices');if(!rows.length){root.innerHTML='<div class="coop-empty">No local service records are currently available.</div>';return;}root.innerHTML=`<div class="coop-toolbar compact"><label><span>Search Booking</span><input id="coopBookingSearch" type="search" placeholder="Booking code, service or worker"></label><label><span>Status</span><select id="coopBookingStatus"><option value="">All statuses</option>${[...new Set(rows.map(x=>x.status).filter(Boolean))].map(x=>`<option value="${esc(x)}">${esc(human(x))}</option>`).join('')}</select></label><span id="coopBookingCount" class="coop-count" aria-live="polite"></span></div><div class="judge-table-wrap"><table class="judge-table coop-table"><thead><tr><th>Booking</th><th>Service</th><th>Worker</th><th>Schedule</th><th>Zone</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr data-booking-row data-search="${esc(`${x.bookingCode||''} ${x.service||''} ${x.worker||''}`.toLowerCase())}" data-status="${esc(x.status||'')}"><td><b>${esc(x.bookingCode||`#${x.id}`)}</b>${x.delayed?'<small class="coop-delay">Schedule attention</small>':''}</td><td>${esc(x.service)}</td><td>${esc(x.worker||'Unassigned')}</td><td>${fmtDate(x.scheduledAt)}</td><td>${esc(x.zone||'—')}</td><td>${badge(x.status)}</td></tr>`).join('')}</tbody></table></div>`;const apply=()=>{const q=String($('#coopBookingSearch')?.value||'').toLowerCase(),s=$('#coopBookingStatus')?.value||'';let n=0;$$('[data-booking-row]',root).forEach(r=>{const ok=(!q||r.dataset.search.includes(q))&&(!s||r.dataset.status===s);r.hidden=!ok;if(ok)n++;});$('#coopBookingCount').textContent=`Showing ${n} of ${rows.length} bookings`;};$('#coopBookingSearch')?.addEventListener('input',apply);$('#coopBookingStatus')?.addEventListener('change',apply);apply();}

  function renderComplaints(d){const rows=d.complaints||[],root=$('#coopComplaints');if(!rows.length){root.innerHTML='<div class="coop-empty">No open or historical complaints are available for this cooperative scope.</div>';return;}root.innerHTML=`<div class="judge-table-wrap"><table class="judge-table coop-table"><thead><tr><th>Complaint</th><th>Booking</th><th>Service</th><th>Status</th><th>Level</th><th>SLA Due</th><th>SLA</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>#${Number(x.id)}</b></td><td>${esc(x.bookingCode||`#${x.bookingId}`)}</td><td>${esc(x.service||'—')}</td><td>${badge(x.status)}</td><td>L${Number(x.escalationLevel||0)}</td><td>${fmtDate(x.slaDueAt)}</td><td>${x.slaBreached?badge('Breached','risk'):badge('Within SLA','ok')}</td></tr>`).join('')}</tbody></table></div><div class="coop-flow"><b>SLA governance:</b><span>L1 Support</span><i>→</i><span>L2 Cooperative</span><i>→</i><span>L3 Federation</span><small>Any simulated time advancement remains labelled DEMO SIMULATION in the connected proof workflow.</small></div>`;}

  function renderCapacity(d){const rows=d.skills||[],req=d.capacityRequests||[],root=$('#coopCapacity');const cards=rows.map(x=>{const demand=Number(x.demand30d||0),avail=Number(x.availableWorkers||0),gap=demand-avail,status=gap>0?'CAPACITY LOW':avail===0?'MONITOR':'BALANCED';return `<article class="coop-cap-card"><span>${esc(x.service)}</span><div><b>Observed demand</b><strong>${demand}</strong></div><div><b>Available workers</b><strong>${avail}</strong></div><div><b>Gap</b><strong>${gap}</strong></div>${badge(status)}</article>`;}).join('');const requests=req.length?`<div class="coop-subhead"><b>Capacity coordination records</b><small>No automatic worker transfer · Worker consent required</small></div><div class="judge-table-wrap"><table class="judge-table coop-table"><thead><tr><th>Request</th><th>Role</th><th>Zone</th><th>Requested</th><th>Approved</th><th>Status</th></tr></thead><tbody>${req.map(x=>`<tr><td>${esc(x.requestCode||`#${x.id}`)}</td><td>${esc(x.role)}</td><td>${esc(x.zone||'—')}</td><td>${Number(x.requestedWorkers||0)}</td><td>${Number(x.approvedWorkers||0)}</td><td>${badge(x.status)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="coop-empty small">No connected capacity request records currently involve this cooperative.</div>';root.innerHTML=`<div class="coop-cap-grid">${cards||'<div class="coop-empty">No local capacity data is available.</div>'}</div>${requests}`;}

  function renderQuality(d){const m=d.metrics||{},root=$('#coopQuality');root.innerHTML=`<div class="coop-quality-grid"><article><span>Completed Services</span><strong>${Number(m.completedServices||0)}</strong><small>Completed / paid local bookings</small></article><article><span>Average Rating</span><strong>${Number(m.averageRating||0).toFixed(2)}</strong><small>Stored ratings only</small></article><article><span>Open Complaints</span><strong>${Number(m.openComplaints||0)}</strong><small>Current grievance load</small></article><article><span>SLA Breaches</span><strong>${Number(m.slaBreaches||0)}</strong><small>Requires operational attention</small></article></div>`;}

  function renderPayments(d){const rows=d.payments||[],root=$('#coopPayments');if(!rows.length){root.innerHTML='<div class="coop-empty">No recorded local payment ledger entries are available.</div>';return;}root.innerHTML=`<div class="judge-table-wrap"><table class="judge-table coop-table"><thead><tr><th>Booking</th><th>Service</th><th>Amount</th><th>Status</th><th>Recorded At</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.bookingCode||`#${x.bookingId}`)}</td><td>${esc(x.service||'—')}</td><td>${money(x.amount)}</td><td>${badge(x.status)}</td><td>${fmtDate(x.createdAt)}</td></tr>`).join('')}</tbody></table></div><p class="coop-note">Connected SIH payment flows remain sandbox/demo where explicitly labelled. This admin view is operational visibility, not a production settlement console.</p>`;}

  function renderTraining(d){const rows=d.trainingRecommendations||[],root=$('#coopTraining');if(!rows.length){root.innerHTML='<div class="coop-empty">No connected training recommendations are recorded for this cooperative.</div>';return;}root.innerHTML=`<div class="judge-table-wrap"><table class="judge-table coop-table"><thead><tr><th>Worker</th><th>Skill</th><th>Recommendation</th><th>Reason</th><th>Status</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.worker)}</td><td>${esc(x.service)}</td><td>${esc(x.trainingName)}</td><td>${esc(x.reason||'—')}</td><td>${badge(x.status)}</td></tr>`).join('')}</tbody></table></div><p class="coop-note"><b>Human approval required.</b> Training recommendation never automatically verifies a worker skill.</p>`;}

  function renderActivity(d){const events=[];(d.services||[]).slice(0,12).forEach(x=>events.push({time:x.createdAt,type:'Booking',title:x.bookingCode||`#${x.id}`,detail:`${x.service} · ${human(x.status)}`}));(d.complaints||[]).slice(0,8).forEach(x=>events.push({time:x.createdAt,type:'Complaint',title:`Complaint #${x.id}`,detail:`${x.bookingCode||''} · L${Number(x.escalationLevel||0)} · ${human(x.status)}`}));(d.capacityRequests||[]).slice(0,6).forEach(x=>events.push({time:x.requestedAt,type:'Capacity',title:x.requestCode||`#${x.id}`,detail:`${x.role} · ${human(x.status)}`}));(d.trainingRecommendations||[]).slice(0,6).forEach(x=>events.push({time:x.createdAt,type:'Training',title:x.worker,detail:`${x.service} · ${human(x.status)}`}));(d.payments||[]).slice(0,8).forEach(x=>events.push({time:x.createdAt,type:'Payment',title:x.bookingCode||`#${x.bookingId}`,detail:`${money(x.amount)} · ${human(x.status)}`}));events.sort((a,b)=>new Date(b.time||0)-new Date(a.time||0));const root=$('#coopActivity');root.innerHTML=events.length?`<div class="coop-activity-list">${events.slice(0,20).map(e=>`<article><span>${esc(e.type)}</span><div><b>${esc(e.title)}</b><p>${esc(e.detail)}</p></div><time>${fmtDate(e.time)}</time></article>`).join('')}</div>`:'<div class="coop-empty">No connected operational records are available yet.</div>';}

  function renderFeatureMatrix(runtime){const features=[['Local Cooperative Workspace','GET /api/cooperative-admin/workspace','workers · bookings · complaints · payments · skills','COOPERATIVE_ADMIN',runtime.workspace?'CONNECTED + READ VERIFIED':'ATTENTION / READ FAILED',runtime.workspace?'ok':'risk'],['Federation-safe Role Scope','cooperative_admin_profiles.cooperative_id','cooperative_admin_profiles · cooperatives','COOPERATIVE_ADMIN',runtime.workspace?'LOCAL SCOPE CONNECTED':'NOT VERIFIED',runtime.workspace?'ok':'warn'],['Worker Identity Verification','POST /api/cooperative-admin/workers/:id/verification','workers · verification audit','COOPERATIVE_ADMIN','CONNECTED · MANUAL WRITE TEST REQUIRED','warn'],['Fair Matching Explanation','GET /api/connected/judge/match/:bookingId','workers · skills · documents · bookings','ADMIN READ',runtime.matching===true?'CONNECTED + READ VERIFIED':runtime.matching===false?'ATTENTION / READ FAILED':'READY AFTER BOOKING',runtime.matching===true?'ok':runtime.matching===false?'risk':'neutral'],['Complaint / SLA','Connected complaint + breach routes','complaints · complaint_events','ADMIN / FEDERATION','CONNECTED · MANUAL WRITE TEST REQUIRED','warn'],['Capacity Exchange','Connected capacity request / approval routes','capacity_requests · capacity_request_workers','ADMIN / FEDERATION','CONNECTED · MANUAL WRITE TEST REQUIRED','warn'],['Service-start Trust','Arrival · identity · customer confirm · start','bookings · job_verifications · service_start_tokens','CUSTOMER / WORKER','CODE-CONNECTED · MANUAL REGRESSION REQUIRED','info'],['Payment / Invoice','Connected commerce routes','payments · invoices · additional_charges','CUSTOMER','SANDBOX · MANUAL REGRESSION REQUIRED','info'],['Statutory Returns / Election / Inspection','No live administrative connector claimed','—','Future authorized integration','FUTURE ADMINISTRATIVE INTEGRATION','neutral'],['Insurance / ESIC / Schemes','No live external integration claimed','—','Future authorized integration','FUTURE AUTHORIZED INTEGRATION','neutral']];$('#coopFeatureMatrix').innerHTML=`<div class="judge-table-wrap"><table class="judge-table coop-table coop-feature-table"><thead><tr><th>Feature</th><th>Frontend / API</th><th>Database</th><th>Authorization</th><th>Status</th></tr></thead><tbody>${features.map(f=>`<tr><td><b>${esc(f[0])}</b></td><td>${esc(f[1])}</td><td>${esc(f[2])}</td><td>${esc(f[3])}</td><td>${badge(f[4],f[5])}</td></tr>`).join('')}</tbody></table></div><p class="coop-note">Read checks may be marked verified after successful runtime response. Write and cross-role flows remain NOT TESTED until an isolated demo transaction is actually executed.</p>`;}

  function ensureDrawer(){let root=$('#coopWorkerDrawer');if(root)return root;root=document.createElement('div');root.id='coopWorkerDrawer';root.className='coop-drawer-root';root.hidden=true;root.innerHTML=`<div class="coop-drawer-backdrop" data-coop-close></div><aside class="coop-drawer" role="dialog" aria-modal="true" aria-labelledby="coopWorkerTitle"><header><div><span>WORKER PROFILE</span><h2 id="coopWorkerTitle">Worker</h2></div><button type="button" data-coop-close>Close</button></header><div id="coopWorkerBody"></div></aside>`;document.body.appendChild(root);root.addEventListener('click',e=>{if(e.target.closest('[data-coop-close]'))closeDrawer();});return root;}
  function openWorker(id,trigger){const w=(workspace?.workers||[]).find(x=>Number(x.id)===Number(id));if(!w)return;const root=ensureDrawer();returnFocus=trigger||document.activeElement;$('#coopWorkerTitle',root).textContent=w.name||`Worker #${id}`;const issues=Number(w.pendingDocuments||0)+Number(w.expiredDocuments||0);$('#coopWorkerBody',root).innerHTML=`<div class="coop-worker-summary"><div><span>Identity</span><b>${badge(w.verificationStatus)}</b></div><div><span>Availability</span><b>${badge(w.availability)}</b></div><div><span>Jobs Completed</span><strong>${Number(w.jobsCompleted||0)}</strong></div><div><span>Rating</span><strong>${Number(w.rating||0).toFixed(1)}</strong></div></div><section><h3>Skills</h3><div class="coop-skill-list">${(w.skills||[]).map(s=>`<span>${esc(s.service)} ${s.verified?badge('Verified','ok'):badge('Pending','warn')}</span>`).join('')||'No skill records'}</div></section><section><h3>Document Readiness</h3><p>${Number(w.pendingDocuments||0)} pending verification · ${Number(w.expiredDocuments||0)} expired</p>${issues?'<div class="coop-warning">Document evidence requires review before treating all eligibility checks as satisfied.</div>':'<div class="coop-success">No document issue is reported by the local workspace aggregate.</div>'}</section><section><h3>Operations</h3><dl><div><dt>Worker ID</dt><dd>#${Number(w.id)}</dd></div><div><dt>Current Jobs</dt><dd>${Number(w.currentJobs||0)}</dd></div><div><dt>Complaints</dt><dd>${Number(w.complaintCount||0)}</dd></div><div><dt>Zone</dt><dd>${esc(w.zone||'—')}</dd></div></dl></section>${String(w.verificationStatus)!=='VERIFIED'?`<section class="coop-verify-action"><h3>Authorized Identity Review</h3><p>Identity verification is a Cooperative Admin action. Skill verification remains independent and is not changed by this action.</p><button type="button" class="btn primary small" data-start-verify="${Number(w.id)}">Review Verification</button><div id="coopVerifyConfirm"></div></section>`:''}`;root.hidden=false;document.body.classList.add('coop-drawer-open');$('[data-start-verify]',root)?.addEventListener('click',e=>showVerificationConfirm(w,e.currentTarget));setTimeout(()=>$('[data-coop-close]',root)?.focus(),0);}
  function closeDrawer(){const root=$('#coopWorkerDrawer');if(!root||root.hidden)return;root.hidden=true;document.body.classList.remove('coop-drawer-open');const t=returnFocus;returnFocus=null;setTimeout(()=>t?.isConnected&&t.focus(),0);}
  function showVerificationConfirm(w,trigger){const host=$('#coopVerifyConfirm');if(!host)return;trigger.disabled=true;host.innerHTML=`<div class="coop-confirm"><label><span>Review note</span><textarea id="coopVerifyReason" rows="3" placeholder="Record the basis for this authorized review"></textarea></label><div><button type="button" class="btn primary small" id="coopVerifySubmit">Confirm Identity Verification</button><button type="button" class="btn secondary small" id="coopVerifyCancel">Cancel</button></div><p id="coopVerifyMessage" aria-live="polite"></p></div>`;$('#coopVerifyCancel',host).onclick=()=>{host.innerHTML='';trigger.disabled=false;trigger.focus();};$('#coopVerifySubmit',host).onclick=async()=>{const reason=String($('#coopVerifyReason',host)?.value||'').trim();const msg=$('#coopVerifyMessage',host),btn=$('#coopVerifySubmit',host);if(reason.length<4){msg.textContent='Add a short review note before confirming.';return;}btn.disabled=true;msg.textContent='Recording authorized verification…';try{await post(`/api/cooperative-admin/workers/${Number(w.id)}/verification`,{status:'VERIFIED',reason});msg.textContent='Identity verification recorded. Worker skills remain independently governed.';await loadWorkspace(true);setTimeout(()=>closeDrawer(),800);}catch(e){msg.textContent=e.status===403?'You do not have permission for this worker.':e.message||'Verification could not be recorded.';btn.disabled=false;}};}

  async function runtimeChecks(){const results=await Promise.allSettled([api('/api/connected/health'),api('/api/auth/me'),api('/api/connected/judge/latest-demo-booking')]);const health=results[0].status==='fulfilled',auth=results[1].status==='fulfilled'&&String(results[1].value?.user?.role||'').toUpperCase()==='COOPERATIVE_ADMIN',latest=results[2].status==='fulfilled'?results[2].value:null;let matching=null;if(latest?.booking?.id){try{await api(`/api/connected/judge/match/${latest.booking.id}`);matching=true}catch{matching=false}}return {health,auth,matching};}

  async function loadWorkspace(force=false){if(refreshPromise&&!force)return refreshPromise;refreshPromise=(async()=>{try{const [d,runtime]=await Promise.all([api('/api/cooperative-admin/workspace'),runtimeChecks()]);workspace=d;renderAttention(d);renderKpis(d);renderToday(d);renderWorkers(d);renderVerification(d);renderSkills(d);renderServices(d);renderComplaints(d);renderCapacity(d);renderQuality(d);renderPayments(d);renderTraining(d);renderActivity(d);renderFeatureMatrix({...runtime,workspace:true});const sync=$('#coopLastSync');if(sync)sync.textContent=`Last sync ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;return d;}catch(e){const root=$('#coopPortal');if(root)root.querySelectorAll('.admin-skeleton').forEach(x=>x.outerHTML='<div class="admin-health-error">Local cooperative data could not be loaded. Use Refresh Local Data to retry.</div>');renderFeatureMatrix({workspace:false,matching:null});throw e;}finally{refreshPromise=null;}})();return refreshPromise;}

  function trapDrawer(e){const root=$('#coopWorkerDrawer');if(!root||root.hidden)return;if(e.key==='Escape'){e.preventDefault();closeDrawer();return;}if(e.key!=='Tab')return;const nodes=$$('button:not([disabled]),textarea:not([disabled]),input:not([disabled]),[href],[tabindex]:not([tabindex="-1"])',root).filter(x=>x.getClientRects().length);if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}

  function enhance(){if(!isCooperative())return;ensureFrame();ensurePortal();if(!workspace)loadWorkspace().catch(()=>{});}
  function schedule(){clearTimeout(timer);timer=setTimeout(enhance,70);}
  function install(){document.addEventListener('keydown',trapDrawer);document.addEventListener('click',e=>{if(e.target.closest?.('#adminHealthRefresh')&&isCooperative())setTimeout(()=>loadWorkspace(true).catch(()=>{}),80);if(e.target.closest?.('[data-judge-role="COOPERATIVE_ADMIN"],#getStarted,#sihJudgeModeBtn,#judgeModeStatusBtn'))setTimeout(schedule,180);},true);observer=new MutationObserver(schedule);observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class','data-admin-role']});schedule();}

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();