(() => {
  'use strict';
  const BACKEND='https://sanpaid-sih-2026.onrender.com';
  const TOKEN_KEY='sanpaid_judge_demo_token_v1';
  const PASSWORD='Demo@2026';
  const ACCOUNTS={
    COOPERATIVE_ADMIN:{email:'admin.connected@sanpaid.demo',label:'Karad Cooperative Admin'},
    FEDERATION_ADMIN:{email:'federation.connected@sanpaid.demo',label:'Federation Admin'}
  };
  let token='';let user=null;let activeComplaintId=null;let activeCapacityId=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const human=s=>({PENDING_WORKER_ACCEPTANCE:'Waiting for Worker Response',FINDING_REPLACEMENT:'Finding Replacement Worker',CUSTOMER_CONFIRMED:'Customer Confirmed',IDENTITY_VERIFIED:'Identity Verified',WORKERS_OFFERED:'Workers Offered · Consent Pending',IN_REVIEW:'Under Review'}[String(s||'')]||String(s||'').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase()));
  const getToken=()=>{try{return sessionStorage.getItem(TOKEN_KEY)||''}catch{return ''}};
  const setToken=v=>{token=v||'';try{v?sessionStorage.setItem(TOKEN_KEY,v):sessionStorage.removeItem(TOKEN_KEY)}catch{}};

  async function api(path,opt={}){
    const headers=new Headers(opt.headers||{});if(opt.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json');if(token||getToken())headers.set('Authorization',`Bearer ${token||getToken()}`);
    const r=await fetch(BACKEND+path,{...opt,headers,mode:'cors',credentials:'omit',cache:'no-store'});const data=await r.json().catch(()=>({}));
    if(!r.ok){const e=new Error(data.message||data.error||`Request failed (${r.status})`);e.status=r.status;throw e;}return data;
  }
  const post=(path,body={})=>api(path,{method:'POST',body:JSON.stringify(body)});

  function shell(){let root=document.getElementById('sihJudgeShell');if(root)return root;root=document.createElement('section');root.id='sihJudgeShell';root.className='judge-hidden';root.innerHTML=`<header class="judge-top"><div><div class="brand">San<span>Paid</span></div><small>Top‑1 SIH Judge Mode · Working Proofs</small></div><div class="judge-top-actions"><span id="judgeHealth" class="judge-live">Checking backend…</span><button class="btn ghost small" id="judgeClose">✕</button></div></header><main class="judge-main" id="judgeContent"></main>`;document.body.appendChild(root);root.querySelector('#judgeClose').onclick=close;return root;}
  async function open(){const root=shell();root.classList.remove('judge-hidden');document.body.style.overflow='hidden';await health();token=getToken();if(token){try{const me=await api('/api/connected/auth/me');user=me.user;return renderDashboard()}catch{setToken('')}}renderLogin();}
  function close(){shell().classList.add('judge-hidden');document.body.style.overflow='';document.body.classList.remove('judge-presentation');}
  async function health(){const el=shell().querySelector('#judgeHealth');try{const h=await api('/api/connected/health');el.textContent=h.ok?'● Backend Online':'Backend unavailable';el.style.color=h.ok?'#91e6b8':'#ffb0b0'}catch{el.textContent='● Backend Offline';el.style.color='#ffb0b0'}}

  function renderLogin(){const c=shell().querySelector('#judgeContent');c.innerHTML=`<div class="judge-login judge-card"><span class="judge-badge">ISOLATED DEMO AUTH</span><h2 style="margin-top:12px">Open SIH Judge Mode</h2><p>Use a dedicated admin identity. This panel reads the same PostgreSQL workflow as the customer and worker devices.</p><div class="judge-grid two" style="margin:16px 0">${Object.entries(ACCOUNTS).map(([role,a])=>`<button class="judge-card" data-judge-role="${role}" style="text-align:left;cursor:pointer"><h3>${role==='COOPERATIVE_ADMIN'?'🏢':'🌐'} ${esc(a.label)}</h3><p>${role==='COOPERATIVE_ADMIN'?'Workforce operations, matching, SLA and capacity request.':'Regional governance and cross-cooperative proof.'}</p><div class="judge-account">${esc(a.email)}</div></button>`).join('')}</div><div id="judgeLoginError"></div><div class="judge-note">Password for isolated SIH demo identities: <b>${PASSWORD}</b></div></div>`;c.querySelectorAll('[data-judge-role]').forEach(b=>b.onclick=()=>login(b.dataset.judgeRole));}
  async function login(role){const c=shell().querySelector('#judgeContent');const error=c.querySelector('#judgeLoginError');if(error)error.innerHTML='<div class="judge-note">Authenticating with shared backend…</div>';try{const a=ACCOUNTS[role];const r=await fetch(BACKEND+'/api/connected/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifier:a.email,password:PASSWORD,role,remember:false}),mode:'cors',credentials:'omit',cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Login failed (${r.status})`);setToken(d.demoToken);user=d.user;renderDashboard();}catch(e){if(error)error.innerHTML=`<div class="judge-error">${esc(e.message)}</div>`}}
  async function logout(){try{await post('/api/connected/auth/logout')}catch{}setToken('');user=null;renderLogin();}

  function renderDashboard(){const c=shell().querySelector('#judgeContent');c.innerHTML=`<section class="judge-hero"><span class="judge-badge">CONNECTED WORKING PROTOTYPE</span><h1>SanPaid Judge Proof Console</h1><p>Demand → Verified Eligibility → Fair Allocation → Worker Choice → Trusted Delivery → Governance → Capacity / Skill Planning.</p><div class="judge-actions"><button class="btn secondary small" id="judgePresentation">Presentation Focus</button><button class="btn danger small" id="judgeLogout">Logout</button></div></section><div class="judge-tabs">${[['overview','Command Center'],['matching','Why This Worker?'],['capacity','Capacity Exchange'],['complaint','Complaint / SLA'],['planning','Demand Planning'],['control','Demo Control']].map(([id,label],i)=>`<button class="judge-tab ${i===0?'active':''}" data-judge-tab="${id}">${label}</button>`).join('')}</div>${['overview','matching','capacity','complaint','planning','control'].map((id,i)=>`<section class="judge-section ${i===0?'active':''}" id="judge-${id}"><div class="judge-card">Loading ${id} proof…</div></section>`).join('')}`;
    c.querySelector('#judgeLogout').onclick=logout;c.querySelector('#judgePresentation').onclick=()=>document.body.classList.toggle('judge-presentation');c.querySelectorAll('[data-judge-tab]').forEach(b=>b.onclick=()=>{c.querySelectorAll('.judge-tab').forEach(x=>x.classList.toggle('active',x===b));c.querySelectorAll('.judge-section').forEach(x=>x.classList.toggle('active',x.id===`judge-${b.dataset.judgeTab}`));loadTab(b.dataset.judgeTab)});loadTab('overview');}
  async function loadTab(id){if(id==='overview')return loadOverview();if(id==='matching')return loadMatching();if(id==='capacity')return loadCapacity();if(id==='complaint')return loadComplaint();if(id==='planning')return loadPlanning();if(id==='control')return loadControl();}
  function errorBox(root,e){root.innerHTML=`<div class="judge-error">${esc(e.message||'This proof could not be loaded.')} <button class="btn secondary small" data-retry>Retry</button></div>`;root.querySelector('[data-retry]')?.addEventListener('click',()=>loadTab(root.id.replace('judge-','')));}

  async function loadOverview(){const root=document.getElementById('judge-overview');root.innerHTML='<div class="judge-card">Loading derived Command Center data…</div>';try{const d=await api('/api/connected/judge/overview');const m=d.metrics||{};root.innerHTML=`<div class="judge-grid"><div class="judge-card judge-kpi"><span>Registered Workers</span><b>${Number(m.totalWorkers||0)}</b><p>Database-derived</p></div><div class="judge-card judge-kpi"><span>Verified Workers</span><b>${Number(m.verifiedWorkers||0)}</b><p>Eligibility source</p></div><div class="judge-card judge-kpi"><span>Available Now</span><b>${Number(m.availableWorkers||0)}</b><p>Verified + available</p></div><div class="judge-card judge-kpi"><span>Open Complaints</span><b>${Number(m.openComplaints||0)}</b><p>SLA-governed</p></div></div><div class="judge-grid two" style="margin-top:12px"><div class="judge-card"><h3>Cooperative Network</h3><div class="judge-coop-list">${(d.cooperatives||[]).map(x=>`<div class="judge-row"><span><b>${esc(x.name)}</b><br><small>${esc(x.city||'Maharashtra')}</small></span><span>${Number(x.available||0)} available / ${Number(x.workers||0)} workers</span></div>`).join('')||'<p>No cooperative data.</p>'}</div></div><div class="judge-card"><h3>Governance Snapshot</h3><div class="judge-row"><span>Active bookings</span><b>${Number(m.activeBookings||0)}</b></div><div class="judge-row"><span>SLA breached</span><b>${Number(m.slaBreached||0)}</b></div><div class="judge-row"><span>Recorded payments</span><b>₹${Number(m.recordedPayments||0).toLocaleString('en-IN')}</b></div><div class="judge-note" style="margin-top:12px">These values are queried from the shared backend. No random dashboard numbers are generated here.</div></div></div>`;}catch(e){errorBox(root,e)}}

  async function loadMatching(){const root=document.getElementById('judge-matching');root.innerHTML='<div class="judge-card">Finding latest Connected Customer booking…</div>';try{const latest=await api('/api/connected/judge/latest-demo-booking');if(!latest.booking){root.innerHTML='<div class="judge-card"><h3>No connected booking yet</h3><p>Create a Customer Connected Demo booking first, then return here.</p></div>';return}const d=await api(`/api/connected/judge/match/${latest.booking.id}`);const checkLabel=k=>({identityVerified:'Identity Verified',skillVerified:'Correct Skill Verified',available:'Worker Available',withinRadius:'Within Policy Radius',documentsValid:'No Blocking Document',noScheduleConflict:'No Schedule Conflict'}[k]||k);const card=x=>`<div class="judge-card"><div class="judge-row"><span><span class="judge-badge">#${x.rank||'—'} ELIGIBLE</span><h3 style="margin-top:8px">${esc(x.name)}</h3><small>${esc(x.cooperative||'Cooperative')} · ${x.distance} KM · Rating ${x.rating}</small></span><b>${x.score??'—'}%</b></div><div class="judge-checks">${Object.entries(x.checks||{}).map(([k,v])=>`<div class="judge-check ${v?'ok':'no'}">${esc(checkLabel(k))}</div>`).join('')}</div></div>`;const excluded=(d.excluded||[])[0];root.innerHTML=`<div class="judge-card"><span class="judge-badge">${esc(d.policy.principle)}</span><h2 style="margin-top:10px">${esc(d.booking.bookingCode)} · ${esc(d.booking.service)}</h2><p>Eligibility gates run before deterministic fair ranking. Default demo radius: ${d.policy.defaultRadiusKm} KM.</p><div class="judge-note">Ranking weights: Distance 45% · Rating 35% · Fairness / workload 20%.</div></div><div class="judge-grid two" style="margin-top:12px">${(d.eligible||[]).slice(0,2).map(card).join('')||'<div class="judge-card">No eligible candidates.</div>'}${excluded?`<div class="judge-card"><span class="judge-badge exclude">EXCLUDED BEFORE RANKING</span><h3 style="margin-top:10px">${esc(excluded.name)}</h3><p>${excluded.distance} KM away — closer does not override verification/safety.</p><div class="judge-checks">${Object.entries(excluded.checks||{}).map(([k,v])=>`<div class="judge-check ${v?'ok':'no'}">${esc(checkLabel(k))}</div>`).join('')}</div><div class="judge-note" style="margin-top:10px">Reason: ${esc((excluded.reasons||[]).join(', ')||'Eligibility requirement not met')}</div></div>`:''}</div>`;}catch(e){errorBox(root,e)}}

  async function loadCapacity(){const root=document.getElementById('judge-capacity');root.innerHTML='<div class="judge-card">Loading capacity exchange state…</div>';try{const d=await api('/api/connected/judge/overview');const latest=(d.capacityRequests||[])[0];activeCapacityId=latest?.id||null;root.innerHTML=`<div class="judge-grid two"><div class="judge-card"><span class="judge-badge demo">DEMO GOVERNANCE SCENARIO</span><h2 style="margin-top:10px">Cross-Cooperative Capacity Exchange</h2><p>Karad Cooperative can request one verified Electrician from Satara. Approval only creates a worker offer — it never silently transfers a worker.</p><div class="judge-actions"><button class="btn primary" id="judgeCapacityCreate">Request Capacity</button>${latest&&latest.status==='REQUESTED'?'<button class="btn secondary" id="judgeCapacityApprove">Approve Request</button>':''}</div><div id="judgeCapacityMsg"></div></div><div class="judge-card"><h3>Latest Capacity Request</h3>${latest?`<div class="judge-row"><span>Request</span><b>${esc(latest.requestCode)}</b></div><div class="judge-row"><span>Status</span><b>${esc(human(latest.status))}</b></div><div class="judge-row"><span>Workers requested</span><b>${Number(latest.requestedWorkers||0)}</b></div><div class="judge-note">After approval, open Worker B Connected Demo. A separate capacity offer appears with Accept / Reject so worker consent is visible.</div>`:'<p>No active demo capacity request.</p>'}</div></div>`;root.querySelector('#judgeCapacityCreate')?.addEventListener('click',async()=>{const msg=root.querySelector('#judgeCapacityMsg');msg.innerHTML='<div class="judge-note">Creating capacity request…</div>';try{const r=await post('/api/connected/judge/capacity/request',{service:'Electrician',requestingCooperativeId:95,providingCooperativeId:96,requestedWorkers:1,zone:'Karad Zone 1'});activeCapacityId=r.request.id;msg.innerHTML='<div class="judge-success">Capacity request created. Federation/provider approval is now required.</div>';setTimeout(loadCapacity,500)}catch(e){msg.innerHTML=`<div class="judge-error">${esc(e.message)}</div>`}});root.querySelector('#judgeCapacityApprove')?.addEventListener('click',async()=>{const msg=root.querySelector('#judgeCapacityMsg');msg.innerHTML='<div class="judge-note">Checking eligible Satara capacity…</div>';try{const r=await post(`/api/connected/judge/capacity/${latest.id}/approve`);msg.innerHTML=`<div class="judge-success">${esc(r.message)}</div>`;setTimeout(loadCapacity,700)}catch(e){msg.innerHTML=`<div class="judge-error">${esc(e.message)}</div>`}});}catch(e){errorBox(root,e)}}

  async function loadComplaint(){const root=document.getElementById('judge-complaint');root.innerHTML='<div class="judge-card">Loading SLA proof…</div>';try{const d=await api('/api/connected/judge/overview');const cp=(d.complaints||[])[0];activeComplaintId=cp?.id||null;let timeline=[];if(activeComplaintId)timeline=await api(`/api/connected/judge/complaints/${activeComplaintId}/timeline`);root.innerHTML=`<div class="judge-grid two"><div class="judge-card"><span class="judge-badge demo">DEMO SIMULATION</span><h2 style="margin-top:10px">Complaint SLA Escalation</h2><p>This advances a clearly labelled demo state; it does not pretend four real hours elapsed.</p><div class="judge-actions"><button class="btn primary" id="judgeComplaintCreate">Create Demo Complaint</button>${cp&&Number(cp.escalationLevel||1)<3?'<button class="btn secondary" id="judgeSlaBreach">Simulate SLA Breach</button>':''}</div><div id="judgeComplaintMsg"></div></div><div class="judge-card"><h3>Current SLA State</h3>${cp?`<div class="judge-row"><span>Status</span><b>${esc(human(cp.status))}</b></div><div class="judge-row"><span>Escalation</span><b>L${Number(cp.escalationLevel||1)}</b></div><div class="judge-row"><span>SLA breached</span><b>${cp.slaBreached?'YES':'NO'}</b></div><div class="judge-timeline" style="margin-top:12px">${timeline.map(x=>`<div class="judge-event"><b>${esc(x.eventType)}</b><p>${esc(x.message)}</p></div>`).join('')}</div>`:'<p>Create a demo complaint after a connected booking exists.</p>'}</div></div>`;root.querySelector('#judgeComplaintCreate')?.addEventListener('click',async()=>{const msg=root.querySelector('#judgeComplaintMsg');msg.innerHTML='<div class="judge-note">Creating L1 demo complaint…</div>';try{await post('/api/connected/judge/complaint-demo');msg.innerHTML='<div class="judge-success">Demo complaint created at L1.</div>';setTimeout(loadComplaint,500)}catch(e){msg.innerHTML=`<div class="judge-error">${esc(e.message)}</div>`}});root.querySelector('#judgeSlaBreach')?.addEventListener('click',async()=>{const msg=root.querySelector('#judgeComplaintMsg');msg.innerHTML='<div class="judge-note">Advancing DEMO SLA state…</div>';try{const r=await post(`/api/connected/judge/complaints/${cp.id}/simulate-breach`);msg.innerHTML=`<div class="judge-success">DEMO SIMULATION: escalated to ${esc(r.label)}.</div>`;setTimeout(loadComplaint,500)}catch(e){msg.innerHTML=`<div class="judge-error">${esc(e.message)}</div>`}});}catch(e){errorBox(root,e)}}

  async function loadPlanning(){const root=document.getElementById('judge-planning');root.innerHTML='<div class="judge-card">Calculating demand and eligible capacity…</div>';try{const d=await api('/api/connected/judge/planning');const gap=Number(d.capacityGap||0);root.innerHTML=`<div class="judge-grid"><div class="judge-card judge-kpi"><span>30-day Demand</span><b>${Number(d.historicalDemand30d||0)}</b><p>Observed bookings</p></div><div class="judge-card judge-kpi"><span>Expected Demand</span><b>${Number(d.expectedDemand||0)}</b><p>${esc(d.forecastMethod)}</p></div><div class="judge-card judge-kpi"><span>Eligible Capacity</span><b>${Number(d.eligibleCapacity||0)}</b><p>Verified + skill + available</p></div><div class="judge-card judge-kpi"><span>Capacity Gap</span><b>${gap>0?'-'+gap:Math.abs(gap)}</b><p>${gap>0?'Shortage':'No shortage detected'}</p></div></div><div class="judge-card" style="margin-top:12px"><span class="judge-badge">Confidence: ${esc(d.confidence)}</span><h3 style="margin-top:10px">AI-Assisted Planning · Advisory</h3><p>${esc(d.claim)}</p><div class="judge-note">Recommended actions: ${(d.recommendedActions||[]).map(human).join(' · ')}</div><p style="margin-top:10px">No fake model accuracy is shown. Low history produces low confidence.</p></div>`;}catch(e){errorBox(root,e)}}

  function loadControl(){const root=document.getElementById('judge-control');root.innerHTML=`<div class="judge-grid two"><div class="judge-card"><h2>Reset Connected SIH Demo</h2><p>Cancels unfinished demo-only bookings, expires demo offers, clears demo SLA/capacity artifacts and restores Worker A / Worker B availability. Real users are not modified.</p><button class="btn danger" id="judgeReset">Reset Demo Dataset</button><div id="judgeResetMsg"></div></div><div class="judge-card"><h3>Judge Demo Sequence</h3><div class="judge-row"><span>1</span><b>Customer Voice</b></div><div class="judge-row"><span>2</span><b>Worker A Reject</b></div><div class="judge-row"><span>3</span><b>Worker B Accept</b></div><div class="judge-row"><span>4</span><b>Dual Verification</b></div><div class="judge-row"><span>5</span><b>Capacity / SLA / Planning</b></div></div></div>`;root.querySelector('#judgeReset').onclick=async()=>{const msg=root.querySelector('#judgeResetMsg');if(!confirm('Reset isolated Connected SIH demo state? Real users will not be changed.'))return;msg.innerHTML='<div class="judge-note">Resetting demo-only state…</div>';try{const r=await post('/api/connected/judge/reset');try{localStorage.removeItem('sanpaid_connected_booking_id')}catch{}msg.innerHTML=`<div class="judge-success">${esc(r.message)}</div>`}catch(e){msg.innerHTML=`<div class="judge-error">${esc(e.message)}</div>`}};}

  function install(){const ctas=document.querySelector('.hero-ctas');if(ctas&&!document.getElementById('sihJudgeModeBtn')){const b=document.createElement('button');b.id='sihJudgeModeBtn';b.type='button';b.className='btn secondary';b.textContent='🏆 SIH Judge Mode';b.onclick=open;ctas.appendChild(b)}const status=document.querySelector('#status .head');if(status&&!document.getElementById('judgeModeStatusBtn')){const b=document.createElement('button');b.id='judgeModeStatusBtn';b.className='btn primary';b.textContent='Open Working Proof Console';b.style.marginTop='10px';b.onclick=open;status.appendChild(b)}}
  window.SanPaidJudgeMode={open,close};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();